// UI-chrome-only translation for the age eligibility calculator — labels,
// buttons, section headings. Exam data itself (category names, qualification
// text, FAQ content) stays English on both locales, same as the resizer's
// own exam names/specs, since translating 85 exams' worth of researched
// content is a different, much larger effort than translating ~40 fixed UI
// strings.
import type { Locale } from "./dictionary";

export const MONTH_NAMES = {
  en: ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
  hi: ["जनवरी", "फ़रवरी", "मार्च", "अप्रैल", "मई", "जून", "जुलाई", "अगस्त", "सितंबर", "अक्टूबर", "नवंबर", "दिसंबर"],
  mr: ["जानेवारी", "फेब्रुवारी", "मार्च", "एप्रिल", "मे", "जून", "जुलै", "ऑगस्ट", "सप्टेंबर", "ऑक्टोबर", "नोव्हेंबर", "डिसेंबर"],
};

export const QUALIFICATION_OPTIONS_BY_LOCALE = {
  en: [
    { value: "below_10th", label: "Below 10th" },
    { value: "10th_pass", label: "10th Pass" },
    { value: "12th_pass", label: "12th Pass" },
    { value: "diploma", label: "D.El.Ed / Diploma in Elementary Education" },
    { value: "graduate", label: "Graduate" },
    { value: "graduate_bed", label: "Graduate + B.Ed" },
    { value: "post_graduate", label: "Post Graduate" },
  ],
  hi: [
    { value: "below_10th", label: "10वीं से कम" },
    { value: "10th_pass", label: "10वीं पास" },
    { value: "12th_pass", label: "12वीं पास" },
    { value: "diploma", label: "D.El.Ed / एलिमेंट्री एजुकेशन डिप्लोमा" },
    { value: "graduate", label: "स्नातक" },
    { value: "graduate_bed", label: "स्नातक + B.Ed" },
    { value: "post_graduate", label: "स्नातकोत्तर" },
  ],
  mr: [
    { value: "below_10th", label: "10 वी पेक्षा कमी" },
    { value: "10th_pass", label: "10 वी पास" },
    { value: "12th_pass", label: "12 वी पास" },
    { value: "diploma", label: "D.El.Ed / प्राथमिक शिक्षण डिप्लोमा" },
    { value: "graduate", label: "पदवीधर" },
    { value: "graduate_bed", label: "पदवीधर + B.Ed" },
    { value: "post_graduate", label: "पदव्युत्तर" },
  ],
};

export const AGE_CALC_STRINGS = {
  en: {
    helpBadge: "Updated for 2026–2027 Exams",
    hubHeadingPrefix: "Check Your ",
    hubHeadingHighlight: "Exam Age Eligibility",
    hubHeadingSuffix: " Instantly",
    hubSubtitle: (otherCount: number) =>
      `Calculate your exact age for UPSC, SSC, Banking, Railways, Teaching and ${otherCount}+ other exams based on official notification dates.`,
    searchPlaceholder: "Search for any exam (e.g. CTET, UPSC IAS, SSC CGL)…",
    allExams: "All Exams",
    showingOf: (shown: number, total: number) => `Showing ${shown} of ${total} exam calculators`,
    noResults: (query: string) => `No exams match "${query}". Try a different keyword.`,
    ageLimit: "Age Limit",
    noLimit: "No Limit",
    minLabel: "Min",
    popular: "Popular",
    checkEligibility: "Check Eligibility",
    enterDetails: (examShortName: string) => `Enter your details to calculate exact age for ${examShortName}.`,
    dateOfBirth: "Date of Birth",
    dobDay: "Day",
    dobMonth: "Month",
    dobYear: "Year",
    dobMinAgeNote: "You must be at least 18 years old.",
    category: "Category",
    qualifications: "Qualifications",
    notificationMonth: "Notification Month",
    notificationYear: "Notification Year",
    calculateEligibility: "Calculate Eligibility",
    invalidDate: "Select your date of birth (day, month and year).",
    awaitingDetailsTitle: "Awaiting Details",
    awaitingDetailsBody: "Enter your date of birth and category to see if you are eligible for this exam.",
    fullyEligible: "Fully Eligible",
    underAgeLimit: "Under Age Limit",
    ageLimitExceeded: "Age Limit Exceeded",
    exactAgeOnCutoff: "Your Exact Age on Cutoff",
    years: "Years",
    months: "Months",
    days: "Days",
    yearLabel: (n: number) => (n === 1 ? "Year" : "Years"),
    monthLabel: (n: number) => (n === 1 ? "Month" : "Months"),
    dayLabel: (n: number) => (n === 1 ? "Day" : "Days"),
    eligibleMessage: "You are eligible for this exam!",
    underAgeMessage: (short: string) => `You are under age. Short by ${short}.`,
    overAgeMessage: (short: string) => `You are over age by ${short}.`,
    resultNote: (examShortName: string) =>
      `Note: This calculation uses the notification month/year you selected above. Official notification dates may vary slightly each year. Always refer to the official ${examShortName} notification.`,
    ageLimitsTableTitle: "Category-wise Age Limits Table",
    ageLimitsTableSubtitle: (examShortName: string) => `Official age boundaries and relaxation rules for ${examShortName}.`,
    tableCategory: "Category",
    tableMinAge: "Min Age",
    tableMaxAge: "Max Age",
    eligibilityCriteriaTitle: "Eligibility Criteria",
    educationalQualification: "Educational Qualification",
    categoryRelaxationTitle: "Category-wise Age Relaxation",
    tableRelaxation: "Relaxation",
    specialRelaxationsTitle: "Special / Additional Relaxations",
    importantNotesTitle: "Important Notes",
    disclaimer: (conductingBody: string) =>
      `Eligibility data above is based on standard official rules. Rules can change — always verify the latest official ${conductingBody} notification before applying.`,
    faqTitle: "Frequently Asked Questions",
    faqSubtitle: (examShortName: string) => `Common queries regarding ${examShortName} age limits, cutoff date, and eligibility.`,
    pageTitle: (examShortName: string, year: number) => `${examShortName} Age Calculator (${year})`,
    metaDescription: (shortName: string, fullName: string) =>
      `Calculate your exact age for ${shortName} (${fullName}) and check category-wise eligibility instantly. Free tool, nothing is uploaded.`,
    conductedBy: "Conducted by",

    // Homepage-only sections (hero CTAs, Popular Calculators, Browse By
    // Category, trust band, How It Works, Aspirant Suite, closing CTA, and
    // the site-level FAQ — distinct from the per-exam FAQ on each exam page).
    exploreCalculators: "Explore Calculators",
    checkExampleEligibility: "Check UPSC Eligibility",
    popularTitle: "Popular Calculators",
    popularSubtitle: "Quickly check eligibility for the most sought-after competitive exams.",
    viewAllExams: (count: number) => `View all ${count} exams`,
    browseByCategoryTitle: "Browse By Category",
    browseByCategorySubtitle: "Find the exact calculator you need from our categorized collections.",
    examsCount: (n: number) => `${n} exams`,
    trustTitle: "Why Aspirants Trust Us",
    trustSubtitle: "We focus entirely on making age eligibility calculation as accurate and frictionless as possible.",
    trustItems: [
      { title: "Highly Accurate", body: "Calculations are based on official notification rules including exact cutoff dates." },
      { title: "Instant Results", body: "No loading screens or waiting. Get your eligibility status in milliseconds." },
      { title: "Category Relaxations", body: "Automatically applies age limit relaxations for OBC, SC/ST, and Ex-Servicemen." },
      { title: "Always Updated", body: "We review our data periodically to reflect the latest official notifications." },
    ],
    howItWorksTitle: "How It Works",
    howItWorksSubtitle: "Three simple steps to clarify your eligibility status. No signup required.",
    howItWorksSteps: [
      { title: "1. Pick Your Exam", body: "Search from our database of 85 Indian competitive exams." },
      { title: "2. Enter Your Details", body: "Input your Date of Birth and category. We'll handle the category-wise age relaxations." },
      { title: "3. Get Instant Result", body: "Instantly see if you're eligible and your exact age on the cutoff date." },
    ],
    suiteTitle: "More Free Tools",
    suiteSubtitle: "Beyond age checks, Clear Cutoff gives you more free, browser-based tools — nothing is ever uploaded.",
    suiteResizerTitle: "Photo & Signature Resizer",
    suiteResizerBody: "Resize and compress your photo or signature to any exam's exact size & KB limit.",
    suiteResizerCta: "Resize Now",
    suiteComingSoon: "Coming soon",
    ctaTitle: "Ready to check your eligibility?",
    ctaSubtitle: "Stop guessing and start preparing with confidence. Find your exam and get instant clarity.",
    ctaButton: "Browse All Exams",
    homeFaqTitle: "Frequently Asked Questions",
    homeFaqSubtitle: "Common questions about age eligibility and how this tool works.",
    homeFaqs: [
      {
        q: "How is the age calculated for exams?",
        a: "We calculate your exact age in years and months as of the notification cutoff date you select, then compare it against the exam's category-wise minimum and maximum age limits.",
      },
      {
        q: "Are category relaxations automatically applied?",
        a: "Yes. Once you pick a category (OBC, SC/ST, PwD, Ex-Servicemen, etc.) on an exam's page, the relevant age relaxation for that category is applied automatically.",
      },
      {
        q: "Is this tool completely free to use?",
        a: "Yes, completely free. It also runs entirely in your browser — no signup, and nothing about your date of birth is ever uploaded or stored.",
      },
      {
        q: "How accurate is the data?",
        a: "Age limits and category relaxations follow the standard, publicly known pattern for each exam. Rules can change year to year — always verify the latest official notification before applying.",
      },
      {
        q: "What if my target exam is not listed?",
        a: "We cover 85 major Indian competitive exams across Civil Services, Banking, Railways, Defence, SSC, Engineering, Medical, State PSC, Teaching, Insurance and Police. If yours isn't listed yet, check back — we review this list periodically.",
      },
    ],
  },
  hi: {
    helpBadge: "2026–2027 परीक्षाओं के लिए अपडेटेड",
    hubHeadingPrefix: "अपनी ",
    hubHeadingHighlight: "परीक्षा आयु पात्रता",
    hubHeadingSuffix: " तुरंत जांचें",
    hubSubtitle: (otherCount: number) =>
      `UPSC, SSC, बैंकिंग, रेलवे, टीचिंग और ${otherCount}+ अन्य परीक्षाओं के लिए आधिकारिक नोटिफिकेशन तारीख के आधार पर अपनी सही उम्र निकालें।`,
    searchPlaceholder: "किसी भी परीक्षा को खोजें (जैसे CTET, UPSC IAS, SSC CGL)…",
    allExams: "सभी परीक्षाएं",
    showingOf: (shown: number, total: number) => `${total} में से ${shown} कैलकुलेटर दिखाए जा रहे हैं`,
    noResults: (query: string) => `"${query}" से कोई परीक्षा मेल नहीं खाती। कोई और शब्द आज़माएं।`,
    ageLimit: "आयु सीमा",
    noLimit: "कोई सीमा नहीं",
    minLabel: "न्यूनतम",
    popular: "लोकप्रिय",
    checkEligibility: "पात्रता जांचें",
    enterDetails: (examShortName: string) => `${examShortName} के लिए सही उम्र निकालने हेतु अपनी जानकारी दर्ज करें।`,
    dateOfBirth: "जन्म तिथि",
    dobDay: "दिन",
    dobMonth: "महीना",
    dobYear: "वर्ष",
    dobMinAgeNote: "आपकी आयु कम से कम 18 वर्ष होनी चाहिए।",
    category: "श्रेणी",
    qualifications: "योग्यता",
    notificationMonth: "नोटिफिकेशन माह",
    notificationYear: "नोटिफिकेशन वर्ष",
    calculateEligibility: "पात्रता की गणना करें",
    invalidDate: "अपनी जन्म तिथि चुनें (दिन, महीना और वर्ष)।",
    awaitingDetailsTitle: "जानकारी की प्रतीक्षा है",
    awaitingDetailsBody: "यह जानने के लिए अपनी जन्म तिथि और श्रेणी दर्ज करें कि आप इस परीक्षा के लिए पात्र हैं या नहीं।",
    fullyEligible: "पूरी तरह पात्र",
    underAgeLimit: "आयु सीमा से कम",
    ageLimitExceeded: "आयु सीमा पार",
    exactAgeOnCutoff: "कटऑफ पर आपकी सही उम्र",
    years: "वर्ष",
    months: "महीने",
    days: "दिन",
    yearLabel: () => "वर्ष",
    monthLabel: () => "महीने",
    dayLabel: () => "दिन",
    eligibleMessage: "आप इस परीक्षा के लिए पात्र हैं!",
    underAgeMessage: (short: string) => `आपकी उम्र कम है। कमी: ${short}।`,
    overAgeMessage: (short: string) => `आपकी उम्र ${short} ज़्यादा है।`,
    resultNote: (examShortName: string) =>
      `नोट: यह गणना ऊपर आपके द्वारा चुने गए नोटिफिकेशन माह/वर्ष पर आधारित है। आधिकारिक नोटिफिकेशन तारीख हर साल थोड़ी बदल सकती है। हमेशा आधिकारिक ${examShortName} नोटिफिकेशन देखें।`,
    ageLimitsTableTitle: "श्रेणी-वार आयु सीमा तालिका",
    ageLimitsTableSubtitle: (examShortName: string) => `${examShortName} के लिए आधिकारिक आयु सीमाएं और छूट नियम।`,
    tableCategory: "श्रेणी",
    tableMinAge: "न्यूनतम आयु",
    tableMaxAge: "अधिकतम आयु",
    eligibilityCriteriaTitle: "पात्रता मानदंड",
    educationalQualification: "शैक्षणिक योग्यता",
    categoryRelaxationTitle: "श्रेणी-वार आयु में छूट",
    tableRelaxation: "छूट",
    specialRelaxationsTitle: "विशेष / अतिरिक्त छूट",
    importantNotesTitle: "महत्वपूर्ण नोट्स",
    disclaimer: (conductingBody: string) =>
      `ऊपर दी गई पात्रता जानकारी मानक आधिकारिक नियमों पर आधारित है। नियम बदल सकते हैं — आवेदन करने से पहले हमेशा नवीनतम आधिकारिक ${conductingBody} नोटिफिकेशन ज़रूर देखें।`,
    faqTitle: "अक्सर पूछे जाने वाले प्रश्न",
    faqSubtitle: (examShortName: string) => `${examShortName} की आयु सीमा, कटऑफ तारीख और पात्रता से जुड़े सामान्य सवाल।`,
    pageTitle: (examShortName: string, year: number) => `${examShortName} आयु कैलकुलेटर (${year})`,
    metaDescription: (shortName: string, fullName: string) =>
      `${shortName} (${fullName}) के लिए अपनी सही उम्र जांचें और श्रेणी-वार आयु पात्रता तुरंत देखें। मुफ़्त टूल, कुछ भी अपलोड नहीं होता।`,
    conductedBy: "आयोजक",

    exploreCalculators: "कैलकुलेटर देखें",
    checkExampleEligibility: "UPSC पात्रता जांचें",
    popularTitle: "लोकप्रिय कैलकुलेटर",
    popularSubtitle: "सबसे ज़्यादा खोजी जाने वाली प्रतियोगी परीक्षाओं की पात्रता तुरंत जांचें।",
    viewAllExams: (count: number) => `सभी ${count} परीक्षाएं देखें`,
    browseByCategoryTitle: "श्रेणी अनुसार खोजें",
    browseByCategorySubtitle: "अपनी श्रेणी के अनुसार सही कैलकुलेटर खोजें।",
    examsCount: (n: number) => `${n} परीक्षाएं`,
    trustTitle: "उम्मीदवार हम पर भरोसा क्यों करते हैं",
    trustSubtitle: "हम आयु पात्रता की गणना को यथासंभव सटीक और आसान बनाने पर पूरा ध्यान देते हैं।",
    trustItems: [
      { title: "उच्च सटीकता", body: "गणना आधिकारिक नोटिफिकेशन नियमों और सही कटऑफ तारीखों पर आधारित है।" },
      { title: "तुरंत परिणाम", body: "कोई लोडिंग या इंतजार नहीं। सेकंडों में अपनी पात्रता स्थिति देखें।" },
      { title: "श्रेणी में छूट", body: "OBC, SC/ST और भूतपूर्व सैनिकों के लिए आयु सीमा में छूट स्वतः लागू होती है।" },
      { title: "हमेशा अपडेटेड", body: "हम नवीनतम आधिकारिक नोटिफिकेशन दर्शाने के लिए अपना डेटा समय-समय पर जांचते हैं।" },
    ],
    howItWorksTitle: "यह कैसे काम करता है",
    howItWorksSubtitle: "अपनी पात्रता स्थिति जानने के तीन आसान चरण। कोई साइनअप ज़रूरी नहीं।",
    howItWorksSteps: [
      { title: "1. अपनी परीक्षा चुनें", body: "85 भारतीय प्रतियोगी परीक्षाओं के डेटाबेस में से खोजें।" },
      { title: "2. अपनी जानकारी दर्ज करें", body: "अपनी जन्म तिथि और श्रेणी दर्ज करें। श्रेणी-वार आयु छूट हम संभाल लेंगे।" },
      { title: "3. तुरंत परिणाम पाएं", body: "तुरंत देखें कि आप पात्र हैं या नहीं, और कटऑफ पर आपकी सही उम्र क्या है।" },
    ],
    suiteTitle: "और मुफ्त टूल्स",
    suiteSubtitle: "आयु जांच के अलावा, Clear Cutoff आपको और भी मुफ्त, ब्राउज़र-आधारित टूल्स देता है — कुछ भी अपलोड नहीं होता।",
    suiteResizerTitle: "फोटो और हस्ताक्षर रीसाइज़र",
    suiteResizerBody: "अपनी फोटो या हस्ताक्षर को किसी भी परीक्षा के सही साइज़ और KB सीमा में रीसाइज़ और कंप्रेस करें।",
    suiteResizerCta: "अभी रीसाइज़ करें",
    suiteComingSoon: "जल्द आ रहा है",
    ctaTitle: "अपनी पात्रता जांचने के लिए तैयार हैं?",
    ctaSubtitle: "अंदाज़ा लगाना बंद करें और आत्मविश्वास के साथ तैयारी शुरू करें। अपनी परीक्षा खोजें और तुरंत स्पष्टता पाएं।",
    ctaButton: "सभी परीक्षाएं देखें",
    homeFaqTitle: "अक्सर पूछे जाने वाले प्रश्न",
    homeFaqSubtitle: "आयु पात्रता और यह टूल कैसे काम करता है, इस बारे में सामान्य सवाल।",
    homeFaqs: [
      {
        q: "परीक्षाओं के लिए उम्र की गणना कैसे होती है?",
        a: "हम आपकी चुनी गई नोटिफिकेशन कटऑफ तारीख के अनुसार आपकी सही उम्र वर्षों और महीनों में निकालते हैं, फिर उसे परीक्षा की श्रेणी-वार न्यूनतम और अधिकतम आयु सीमा से तुलना करते हैं।",
      },
      {
        q: "क्या श्रेणी में छूट अपने आप लागू हो जाती है?",
        a: "हां। किसी परीक्षा के पेज पर श्रेणी (OBC, SC/ST, PwD, भूतपूर्व सैनिक आदि) चुनते ही उस श्रेणी की संबंधित आयु छूट अपने आप लागू हो जाती है।",
      },
      {
        q: "क्या यह टूल पूरी तरह मुफ्त है?",
        a: "हां, पूरी तरह मुफ्त। यह पूरी तरह आपके ब्राउज़र में चलता है — कोई साइनअप नहीं, और आपकी जन्म तिथि कभी अपलोड या स्टोर नहीं होती।",
      },
      {
        q: "डेटा कितना सटीक है?",
        a: "आयु सीमा और श्रेणी छूट हर परीक्षा के मानक, सार्वजनिक रूप से ज्ञात पैटर्न का पालन करती हैं। नियम हर साल बदल सकते हैं — आवेदन से पहले हमेशा नवीनतम आधिकारिक नोटिफिकेशन ज़रूर देखें।",
      },
      {
        q: "अगर मेरी परीक्षा लिस्ट में नहीं है तो?",
        a: "हम Civil Services, Banking, Railways, Defence, SSC, Engineering, Medical, State PSC, Teaching, Insurance और Police में 85 प्रमुख भारतीय प्रतियोगी परीक्षाएं कवर करते हैं। अगर आपकी अभी लिस्ट में नहीं है, तो दोबारा देखें — हम यह लिस्ट समय-समय पर अपडेट करते हैं।",
      },
    ],
  },
  mr: {
    helpBadge: "2026–2027 परीक्षांसाठी अपडेटेड",
    hubHeadingPrefix: "तुमची ",
    hubHeadingHighlight: "परीक्षा वयोमर्यादा पात्रता",
    hubHeadingSuffix: " तात्काळ तपासा",
    hubSubtitle: (otherCount: number) =>
      `UPSC, SSC, बँकिंग, रेल्वे, टीचिंग आणि ${otherCount}+ इतर परीक्षांसाठी अधिकृत अधिसूचना तारखेनुसार तुमचे अचूक वय काढा.`,
    searchPlaceholder: "कोणतीही परीक्षा शोधा (उदा. CTET, UPSC IAS, SSC CGL)…",
    allExams: "सर्व परीक्षा",
    showingOf: (shown: number, total: number) => `${total} पैकी ${shown} कॅल्क्युलेटर दाखवत आहोत`,
    noResults: (query: string) => `"${query}" शी जुळणारी कोणतीही परीक्षा नाही. वेगळा शब्द वापरून पहा.`,
    ageLimit: "वयोमर्यादा",
    noLimit: "मर्यादा नाही",
    minLabel: "किमान",
    popular: "लोकप्रिय",
    checkEligibility: "पात्रता तपासा",
    enterDetails: (examShortName: string) => `${examShortName} साठी अचूक वय काढण्यासाठी तुमची माहिती टाका.`,
    dateOfBirth: "जन्मतारीख",
    dobDay: "दिवस",
    dobMonth: "महिना",
    dobYear: "वर्ष",
    dobMinAgeNote: "तुमचे वय किमान 18 वर्षे असणे आवश्यक आहे.",
    category: "श्रेणी",
    qualifications: "पात्रता",
    notificationMonth: "अधिसूचना महिना",
    notificationYear: "अधिसूचना वर्ष",
    calculateEligibility: "पात्रता मोजा",
    invalidDate: "तुमची जन्मतारीख निवडा (दिवस, महिना आणि वर्ष).",
    awaitingDetailsTitle: "माहितीची प्रतीक्षा आहे",
    awaitingDetailsBody: "तुम्ही या परीक्षेसाठी पात्र आहात का हे पाहण्यासाठी तुमची जन्मतारीख आणि श्रेणी टाका.",
    fullyEligible: "पूर्णपणे पात्र",
    underAgeLimit: "वयोमर्यादेपेक्षा कमी",
    ageLimitExceeded: "वयोमर्यादा ओलांडली",
    exactAgeOnCutoff: "कटऑफवर तुमचे अचूक वय",
    years: "वर्षे",
    months: "महिने",
    days: "दिवस",
    yearLabel: () => "वर्षे",
    monthLabel: () => "महिने",
    dayLabel: () => "दिवस",
    eligibleMessage: "तुम्ही या परीक्षेसाठी पात्र आहात!",
    underAgeMessage: (short: string) => `तुमचे वय कमी आहे. कमतरता: ${short}.`,
    overAgeMessage: (short: string) => `तुमचे वय ${short} ने जास्त आहे.`,
    resultNote: (examShortName: string) =>
      `टीप: ही गणना तुम्ही वर निवडलेल्या अधिसूचना महिना/वर्षावर आधारित आहे. अधिकृत अधिसूचना तारीख दरवर्षी थोडी बदलू शकते. नेहमी अधिकृत ${examShortName} अधिसूचना पहा.`,
    ageLimitsTableTitle: "श्रेणीनुसार वयोमर्यादा तक्ता",
    ageLimitsTableSubtitle: (examShortName: string) => `${examShortName} साठी अधिकृत वयोमर्यादा आणि सवलत नियम.`,
    tableCategory: "श्रेणी",
    tableMinAge: "किमान वय",
    tableMaxAge: "कमाल वय",
    eligibilityCriteriaTitle: "पात्रता निकष",
    educationalQualification: "शैक्षणिक पात्रता",
    categoryRelaxationTitle: "श्रेणीनुसार वयात सवलत",
    tableRelaxation: "सवलत",
    specialRelaxationsTitle: "विशेष / अतिरिक्त सवलती",
    importantNotesTitle: "महत्त्वाच्या सूचना",
    disclaimer: (conductingBody: string) =>
      `वरील पात्रता माहिती मानक अधिकृत नियमांवर आधारित आहे. नियम बदलू शकतात — अर्ज करण्यापूर्वी नेहमी नवीनतम अधिकृत ${conductingBody} अधिसूचना पडताळून पहा.`,
    faqTitle: "वारंवार विचारले जाणारे प्रश्न",
    faqSubtitle: (examShortName: string) => `${examShortName} च्या वयोमर्यादा, कटऑफ तारीख आणि पात्रतेबाबत सामान्य प्रश्न.`,
    pageTitle: (examShortName: string, year: number) => `${examShortName} वय कॅल्क्युलेटर (${year})`,
    metaDescription: (shortName: string, fullName: string) =>
      `${shortName} (${fullName}) साठी तुमचे अचूक वय तपासा आणि श्रेणीनिहाय वय पात्रता त्वरित पहा. मोफत टूल, काहीही अपलोड होत नाही.`,
    conductedBy: "आयोजक",

    exploreCalculators: "कॅल्क्युलेटर पहा",
    checkExampleEligibility: "UPSC पात्रता तपासा",
    popularTitle: "लोकप्रिय कॅल्क्युलेटर",
    popularSubtitle: "सर्वाधिक शोधल्या जाणाऱ्या स्पर्धा परीक्षांची पात्रता तात्काळ तपासा.",
    viewAllExams: (count: number) => `सर्व ${count} परीक्षा पहा`,
    browseByCategoryTitle: "श्रेणीनुसार शोधा",
    browseByCategorySubtitle: "आमच्या वर्गीकृत संग्रहातून तुम्हाला हवे असलेले नेमके कॅल्क्युलेटर शोधा.",
    examsCount: (n: number) => `${n} परीक्षा`,
    trustTitle: "उमेदवार आमच्यावर विश्वास का ठेवतात",
    trustSubtitle: "वयोमर्यादा पात्रता गणना शक्य तितकी अचूक आणि सोपी बनवण्यावर आमचे पूर्ण लक्ष आहे.",
    trustItems: [
      { title: "अत्यंत अचूक", body: "गणना अचूक कटऑफ तारखांसह अधिकृत अधिसूचना नियमांवर आधारित आहे." },
      { title: "तात्काळ निकाल", body: "कोणतीही लोडिंग स्क्रीन किंवा प्रतीक्षा नाही. काही मिलिसेकंदांत तुमची पात्रता स्थिती मिळवा." },
      { title: "श्रेणी सवलती", body: "OBC, SC/ST आणि माजी सैनिकांसाठी वयोमर्यादा सवलती आपोआप लागू होतात." },
      { title: "नेहमी अपडेटेड", body: "नवीनतम अधिकृत अधिसूचना प्रतिबिंबित करण्यासाठी आम्ही आमचा डेटा वेळोवेळी तपासतो." },
    ],
    howItWorksTitle: "हे कसे काम करते",
    howItWorksSubtitle: "तुमची पात्रता स्थिती स्पष्ट करण्यासाठी तीन सोप्या स्टेप्स. साइनअपची गरज नाही.",
    howItWorksSteps: [
      { title: "1. तुमची परीक्षा निवडा", body: "85 भारतीय स्पर्धा परीक्षांच्या आमच्या डेटाबेसमधून शोधा." },
      { title: "2. तुमची माहिती टाका", body: "तुमची जन्मतारीख आणि श्रेणी टाका. श्रेणीनुसार वयात सवलती आम्ही हाताळू." },
      { title: "3. तात्काळ निकाल मिळवा", body: "तुम्ही पात्र आहात का आणि कटऑफ तारखेला तुमचे अचूक वय काय आहे ते तात्काळ पहा." },
    ],
    suiteTitle: "अधिक मोफत टूल्स",
    suiteSubtitle: "वय तपासण्याव्यतिरिक्त, Clear Cutoff तुम्हाला आणखी मोफत, ब्राउझर-आधारित टूल्स देते — काहीही कधीही अपलोड होत नाही.",
    suiteResizerTitle: "फोटो आणि स्वाक्षरी रिसाइझर",
    suiteResizerBody: "तुमचा फोटो किंवा स्वाक्षरी कोणत्याही परीक्षेच्या अचूक आकार आणि KB मर्यादेत रिसाइज आणि कंप्रेस करा.",
    suiteResizerCta: "आता रिसाइज करा",
    suiteComingSoon: "लवकरच येत आहे",
    ctaTitle: "तुमची पात्रता तपासण्यासाठी तयार आहात?",
    ctaSubtitle: "अंदाज लावणे थांबवा आणि आत्मविश्वासाने तयारी सुरू करा. तुमची परीक्षा शोधा आणि तात्काळ स्पष्टता मिळवा.",
    ctaButton: "सर्व परीक्षा पहा",
    homeFaqTitle: "वारंवार विचारले जाणारे प्रश्न",
    homeFaqSubtitle: "वयोमर्यादा पात्रता आणि हे टूल कसे कार्य करते याबद्दल सामान्य प्रश्न.",
    homeFaqs: [
      {
        q: "परीक्षांसाठी वयाची गणना कशी केली जाते?",
        a: "तुम्ही निवडलेल्या अधिसूचना कटऑफ तारखेनुसार आम्ही तुमचे अचूक वय वर्षे आणि महिन्यांत काढतो, नंतर ते परीक्षेच्या श्रेणीनुसार किमान आणि कमाल वयोमर्यादेशी तुलना करतो.",
      },
      {
        q: "श्रेणी सवलती आपोआप लागू होतात का?",
        a: "हो. परीक्षेच्या पानावर एकदा तुम्ही श्रेणी (OBC, SC/ST, PwD, माजी सैनिक इ.) निवडली की, त्या श्रेणीसाठी संबंधित वय सवलत आपोआप लागू होते.",
      },
      {
        q: "हे टूल वापरण्यासाठी पूर्णपणे मोफत आहे का?",
        a: "हो, पूर्णपणे मोफत. हे पूर्णपणे तुमच्या ब्राउझरमध्ये चालते — साइनअपची गरज नाही, आणि तुमच्या जन्मतारखेबद्दल काहीही कधीही अपलोड किंवा साठवले जात नाही.",
      },
      {
        q: "डेटा किती अचूक आहे?",
        a: "वयोमर्यादा आणि श्रेणी सवलती प्रत्येक परीक्षेच्या मानक, सार्वजनिकरीत्या ज्ञात पॅटर्नचे पालन करतात. नियम दरवर्षी बदलू शकतात — अर्ज करण्यापूर्वी नेहमी नवीनतम अधिकृत अधिसूचना पडताळून पहा.",
      },
      {
        q: "माझी लक्ष्य परीक्षा यादीत नसेल तर?",
        a: "आम्ही Civil Services, Banking, Railways, Defence, SSC, Engineering, Medical, State PSC, Teaching, Insurance आणि Police मधील 85 प्रमुख भारतीय स्पर्धा परीक्षा कव्हर करतो. तुमची अजून यादीत नसेल, तर पुन्हा तपासा — आम्ही ही यादी वेळोवेळी अद्ययावत करतो.",
      },
    ],
  },
};

export function getAgeCalcStrings(locale?: Locale) {
  if (locale === "hi") return AGE_CALC_STRINGS.hi;
  if (locale === "mr") return AGE_CALC_STRINGS.mr;
  return AGE_CALC_STRINGS.en;
}
