// UI-chrome-only translation for the age eligibility calculator — labels,
// buttons, section headings. Exam data itself (category names, qualification
// text, FAQ content) stays English on both locales, same as the resizer's
// own exam names/specs, since translating 85 exams' worth of researched
// content is a different, much larger effort than translating ~40 fixed UI
// strings.
import type { Locale } from "./dictionary";

export const MONTH_NAMES = {
  en: ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
  hi: ["जनवरी", "फ़रवरी", "मार्च", "अप्रैल", "मई", "जून", "जुलाई", "अगस्त", "सितंबर", "अक्टूबर", "नवंबर", "दिसंबर"],
};

export const QUALIFICATION_OPTIONS_BY_LOCALE = {
  en: [
    { value: "below_10th", label: "Below 10th" },
    { value: "10th_pass", label: "10th Pass" },
    { value: "12th_pass", label: "12th Pass" },
    { value: "diploma", label: "D.El.Ed / Diploma in Elementary Education" },
    { value: "graduate", label: "Graduate" },
    { value: "graduate_bed", label: "Graduate + B.Ed" },
    { value: "post_graduate", label: "Post Graduate" },
  ],
  hi: [
    { value: "below_10th", label: "10वीं से कम" },
    { value: "10th_pass", label: "10वीं पास" },
    { value: "12th_pass", label: "12वीं पास" },
    { value: "diploma", label: "D.El.Ed / एलिमेंट्री एजुकेशन डिप्लोमा" },
    { value: "graduate", label: "स्नातक" },
    { value: "graduate_bed", label: "स्नातक + B.Ed" },
    { value: "post_graduate", label: "स्नातकोत्तर" },
  ],
};

export const AGE_CALC_STRINGS = {
  en: {
    helpBadge: "Updated for 2026–2027 Exams",
    hubHeadingPrefix: "Check Your ",
    hubHeadingHighlight: "Exam Age Eligibility",
    hubHeadingSuffix: " Instantly",
    hubSubtitle: (otherCount: number) =>
      `Calculate your exact age for UPSC, SSC, Banking, Railways, Teaching and ${otherCount}+ other exams based on official notification dates.`,
    searchPlaceholder: "Search for any exam (e.g. CTET, UPSC IAS, SSC CGL)…",
    allExams: "All Exams",
    showingOf: (shown: number, total: number) => `Showing ${shown} of ${total} exam calculators`,
    noResults: (query: string) => `No exams match "${query}". Try a different keyword.`,
    ageLimit: "Age Limit",
    noLimit: "No Limit",
    minLabel: "Min",
    popular: "Popular",
    checkEligibility: "Check Eligibility",
    enterDetails: (examShortName: string) => `Enter your details to calculate exact age for ${examShortName}.`,
    dateOfBirth: "Date of Birth",
    category: "Category",
    qualifications: "Qualifications",
    notificationMonth: "Notification Month",
    notificationYear: "Notification Year",
    calculateEligibility: "Calculate Eligibility",
    invalidDate: "Enter a valid date as DD/MM/YYYY.",
    awaitingDetailsTitle: "Awaiting Details",
    awaitingDetailsBody: "Enter your date of birth and category to see if you are eligible for this exam.",
    fullyEligible: "Fully Eligible",
    underAgeLimit: "Under Age Limit",
    ageLimitExceeded: "Age Limit Exceeded",
    exactAgeOnCutoff: "Your Exact Age on Cutoff",
    years: "Years",
    months: "Months",
    eligibleMessage: "You are eligible for this exam!",
    underAgeMessage: (short: string) => `You are under age. Short by ${short}.`,
    overAgeMessage: (short: string) => `You are over age by ${short}.`,
    resultNote: (examShortName: string) =>
      `Note: This calculation uses the notification month/year you selected above. Official notification dates may vary slightly each year. Always refer to the official ${examShortName} notification.`,
    ageLimitsTableTitle: "Category-wise Age Limits Table",
    ageLimitsTableSubtitle: (examShortName: string) => `Official age boundaries and relaxation rules for ${examShortName}.`,
    tableCategory: "Category",
    tableMinAge: "Min Age",
    tableMaxAge: "Max Age",
    eligibilityCriteriaTitle: "Eligibility Criteria",
    educationalQualification: "Educational Qualification",
    categoryRelaxationTitle: "Category-wise Age Relaxation",
    tableRelaxation: "Relaxation",
    specialRelaxationsTitle: "Special / Additional Relaxations",
    importantNotesTitle: "Important Notes",
    disclaimer: (conductingBody: string) =>
      `Eligibility data above is based on standard official rules. Rules can change — always verify the latest official ${conductingBody} notification before applying.`,
    faqTitle: "Frequently Asked Questions",
    faqSubtitle: (examShortName: string) => `Common queries regarding ${examShortName} age limits, cutoff date, and eligibility.`,
    pageTitle: (examShortName: string, year: number) => `${examShortName} Age Calculator (${year})`,
    conductedBy: "Conducted by",

    // Homepage-only sections (hero CTAs, Popular Calculators, Browse By
    // Category, trust band, How It Works, Aspirant Suite, closing CTA, and
    // the site-level FAQ — distinct from the per-exam FAQ on each exam page).
    exploreCalculators: "Explore Calculators",
    checkExampleEligibility: "Check UPSC Eligibility",
    popularTitle: "Popular Calculators",
    popularSubtitle: "Quickly check eligibility for the most sought-after competitive exams.",
    viewAllExams: (count: number) => `View all ${count} exams`,
    browseByCategoryTitle: "Browse By Category",
    browseByCategorySubtitle: "Find the exact calculator you need from our categorized collections.",
    examsCount: (n: number) => `${n} exams`,
    trustTitle: "Why Aspirants Trust Us",
    trustSubtitle: "We focus entirely on making age eligibility calculation as accurate and frictionless as possible.",
    trustItems: [
      { title: "Highly Accurate", body: "Calculations are based on official notification rules including exact cutoff dates." },
      { title: "Instant Results", body: "No loading screens or waiting. Get your eligibility status in milliseconds." },
      { title: "Category Relaxations", body: "Automatically applies age limit relaxations for OBC, SC/ST, and Ex-Servicemen." },
      { title: "Always Updated", body: "We review our data periodically to reflect the latest official notifications." },
    ],
    howItWorksTitle: "How It Works",
    howItWorksSubtitle: "Three simple steps to clarify your eligibility status. No signup required.",
    howItWorksSteps: [
      { title: "1. Pick Your Exam", body: "Search from our database of 85 Indian competitive exams." },
      { title: "2. Enter Your Details", body: "Input your Date of Birth and category. We'll handle the category-wise age relaxations." },
      { title: "3. Get Instant Result", body: "Instantly see if you're eligible and your exact age on the cutoff date." },
    ],
    suiteTitle: "More Free Tools",
    suiteSubtitle: "Beyond age checks, Clear Cutoff gives you more free, browser-based tools — nothing is ever uploaded.",
    suiteResizerTitle: "Photo & Signature Resizer",
    suiteResizerBody: "Resize and compress your photo or signature to any exam's exact size & KB limit.",
    suiteResizerCta: "Resize Now",
    suiteComingSoon: "Coming soon",
    ctaTitle: "Ready to check your eligibility?",
    ctaSubtitle: "Stop guessing and start preparing with confidence. Find your exam and get instant clarity.",
    ctaButton: "Browse All Exams",
    homeFaqTitle: "Frequently Asked Questions",
    homeFaqSubtitle: "Common questions about age eligibility and how this tool works.",
    homeFaqs: [
      {
        q: "How is the age calculated for exams?",
        a: "We calculate your exact age in years and months as of the notification cutoff date you select, then compare it against the exam's category-wise minimum and maximum age limits.",
      },
      {
        q: "Are category relaxations automatically applied?",
        a: "Yes. Once you pick a category (OBC, SC/ST, PwD, Ex-Servicemen, etc.) on an exam's page, the relevant age relaxation for that category is applied automatically.",
      },
      {
        q: "Is this tool completely free to use?",
        a: "Yes, completely free. It also runs entirely in your browser — no signup, and nothing about your date of birth is ever uploaded or stored.",
      },
      {
        q: "How accurate is the data?",
        a: "Age limits and category relaxations follow the standard, publicly known pattern for each exam. Rules can change year to year — always verify the latest official notification before applying.",
      },
      {
        q: "What if my target exam is not listed?",
        a: "We cover 85 major Indian competitive exams across Civil Services, Banking, Railways, Defence, SSC, Engineering, Medical, State PSC, Teaching, Insurance and Police. If yours isn't listed yet, check back — we review this list periodically.",
      },
    ],
  },
  hi: {
    helpBadge: "2026–2027 परीक्षाओं के लिए अपडेटेड",
    hubHeadingPrefix: "अपनी ",
    hubHeadingHighlight: "परीक्षा आयु पात्रता",
    hubHeadingSuffix: " तुरंत जांचें",
    hubSubtitle: (otherCount: number) =>
      `UPSC, SSC, बैंकिंग, रेलवे, टीचिंग और ${otherCount}+ अन्य परीक्षाओं के लिए आधिकारिक नोटिफिकेशन तारीख के आधार पर अपनी सही उम्र निकालें।`,
    searchPlaceholder: "किसी भी परीक्षा को खोजें (जैसे CTET, UPSC IAS, SSC CGL)…",
    allExams: "सभी परीक्षाएं",
    showingOf: (shown: number, total: number) => `${total} में से ${shown} कैलकुलेटर दिखाए जा रहे हैं`,
    noResults: (query: string) => `"${query}" से कोई परीक्षा मेल नहीं खाती। कोई और शब्द आज़माएं।`,
    ageLimit: "आयु सीमा",
    noLimit: "कोई सीमा नहीं",
    minLabel: "न्यूनतम",
    popular: "लोकप्रिय",
    checkEligibility: "पात्रता जांचें",
    enterDetails: (examShortName: string) => `${examShortName} के लिए सही उम्र निकालने हेतु अपनी जानकारी दर्ज करें।`,
    dateOfBirth: "जन्म तिथि",
    category: "श्रेणी",
    qualifications: "योग्यता",
    notificationMonth: "नोटिफिकेशन माह",
    notificationYear: "नोटिफिकेशन वर्ष",
    calculateEligibility: "पात्रता की गणना करें",
    invalidDate: "DD/MM/YYYY प्रारूप में सही तारीख दर्ज करें।",
    awaitingDetailsTitle: "जानकारी की प्रतीक्षा है",
    awaitingDetailsBody: "यह जानने के लिए अपनी जन्म तिथि और श्रेणी दर्ज करें कि आप इस परीक्षा के लिए पात्र हैं या नहीं।",
    fullyEligible: "पूरी तरह पात्र",
    underAgeLimit: "आयु सीमा से कम",
    ageLimitExceeded: "आयु सीमा पार",
    exactAgeOnCutoff: "कटऑफ पर आपकी सही उम्र",
    years: "वर्ष",
    months: "महीने",
    eligibleMessage: "आप इस परीक्षा के लिए पात्र हैं!",
    underAgeMessage: (short: string) => `आपकी उम्र कम है। कमी: ${short}।`,
    overAgeMessage: (short: string) => `आपकी उम्र ${short} ज़्यादा है।`,
    resultNote: (examShortName: string) =>
      `नोट: यह गणना ऊपर आपके द्वारा चुने गए नोटिफिकेशन माह/वर्ष पर आधारित है। आधिकारिक नोटिफिकेशन तारीख हर साल थोड़ी बदल सकती है। हमेशा आधिकारिक ${examShortName} नोटिफिकेशन देखें।`,
    ageLimitsTableTitle: "श्रेणी-वार आयु सीमा तालिका",
    ageLimitsTableSubtitle: (examShortName: string) => `${examShortName} के लिए आधिकारिक आयु सीमाएं और छूट नियम।`,
    tableCategory: "श्रेणी",
    tableMinAge: "न्यूनतम आयु",
    tableMaxAge: "अधिकतम आयु",
    eligibilityCriteriaTitle: "पात्रता मानदंड",
    educationalQualification: "शैक्षणिक योग्यता",
    categoryRelaxationTitle: "श्रेणी-वार आयु में छूट",
    tableRelaxation: "छूट",
    specialRelaxationsTitle: "विशेष / अतिरिक्त छूट",
    importantNotesTitle: "महत्वपूर्ण नोट्स",
    disclaimer: (conductingBody: string) =>
      `ऊपर दी गई पात्रता जानकारी मानक आधिकारिक नियमों पर आधारित है। नियम बदल सकते हैं — आवेदन करने से पहले हमेशा नवीनतम आधिकारिक ${conductingBody} नोटिफिकेशन ज़रूर देखें।`,
    faqTitle: "अक्सर पूछे जाने वाले प्रश्न",
    faqSubtitle: (examShortName: string) => `${examShortName} की आयु सीमा, कटऑफ तारीख और पात्रता से जुड़े सामान्य सवाल।`,
    pageTitle: (examShortName: string, year: number) => `${examShortName} आयु कैलकुलेटर (${year})`,
    conductedBy: "आयोजक",

    exploreCalculators: "कैलकुलेटर देखें",
    checkExampleEligibility: "UPSC पात्रता जांचें",
    popularTitle: "लोकप्रिय कैलकुलेटर",
    popularSubtitle: "सबसे ज़्यादा खोजी जाने वाली प्रतियोगी परीक्षाओं की पात्रता तुरंत जांचें।",
    viewAllExams: (count: number) => `सभी ${count} परीक्षाएं देखें`,
    browseByCategoryTitle: "श्रेणी अनुसार खोजें",
    browseByCategorySubtitle: "अपनी श्रेणी के अनुसार सही कैलकुलेटर खोजें।",
    examsCount: (n: number) => `${n} परीक्षाएं`,
    trustTitle: "उम्मीदवार हम पर भरोसा क्यों करते हैं",
    trustSubtitle: "हम आयु पात्रता की गणना को यथासंभव सटीक और आसान बनाने पर पूरा ध्यान देते हैं।",
    trustItems: [
      { title: "उच्च सटीकता", body: "गणना आधिकारिक नोटिफिकेशन नियमों और सही कटऑफ तारीखों पर आधारित है।" },
      { title: "तुरंत परिणाम", body: "कोई लोडिंग या इंतजार नहीं। सेकंडों में अपनी पात्रता स्थिति देखें।" },
      { title: "श्रेणी में छूट", body: "OBC, SC/ST और भूतपूर्व सैनिकों के लिए आयु सीमा में छूट स्वतः लागू होती है।" },
      { title: "हमेशा अपडेटेड", body: "हम नवीनतम आधिकारिक नोटिफिकेशन दर्शाने के लिए अपना डेटा समय-समय पर जांचते हैं।" },
    ],
    howItWorksTitle: "यह कैसे काम करता है",
    howItWorksSubtitle: "अपनी पात्रता स्थिति जानने के तीन आसान चरण। कोई साइनअप ज़रूरी नहीं।",
    howItWorksSteps: [
      { title: "1. अपनी परीक्षा चुनें", body: "85 भारतीय प्रतियोगी परीक्षाओं के डेटाबेस में से खोजें।" },
      { title: "2. अपनी जानकारी दर्ज करें", body: "अपनी जन्म तिथि और श्रेणी दर्ज करें। श्रेणी-वार आयु छूट हम संभाल लेंगे।" },
      { title: "3. तुरंत परिणाम पाएं", body: "तुरंत देखें कि आप पात्र हैं या नहीं, और कटऑफ पर आपकी सही उम्र क्या है।" },
    ],
    suiteTitle: "और मुफ्त टूल्स",
    suiteSubtitle: "आयु जांच के अलावा, Clear Cutoff आपको और भी मुफ्त, ब्राउज़र-आधारित टूल्स देता है — कुछ भी अपलोड नहीं होता।",
    suiteResizerTitle: "फोटो और हस्ताक्षर रीसाइज़र",
    suiteResizerBody: "अपनी फोटो या हस्ताक्षर को किसी भी परीक्षा के सही साइज़ और KB सीमा में रीसाइज़ और कंप्रेस करें।",
    suiteResizerCta: "अभी रीसाइज़ करें",
    suiteComingSoon: "जल्द आ रहा है",
    ctaTitle: "अपनी पात्रता जांचने के लिए तैयार हैं?",
    ctaSubtitle: "अंदाज़ा लगाना बंद करें और आत्मविश्वास के साथ तैयारी शुरू करें। अपनी परीक्षा खोजें और तुरंत स्पष्टता पाएं।",
    ctaButton: "सभी परीक्षाएं देखें",
    homeFaqTitle: "अक्सर पूछे जाने वाले प्रश्न",
    homeFaqSubtitle: "आयु पात्रता और यह टूल कैसे काम करता है, इस बारे में सामान्य सवाल।",
    homeFaqs: [
      {
        q: "परीक्षाओं के लिए उम्र की गणना कैसे होती है?",
        a: "हम आपकी चुनी गई नोटिफिकेशन कटऑफ तारीख के अनुसार आपकी सही उम्र वर्षों और महीनों में निकालते हैं, फिर उसे परीक्षा की श्रेणी-वार न्यूनतम और अधिकतम आयु सीमा से तुलना करते हैं।",
      },
      {
        q: "क्या श्रेणी में छूट अपने आप लागू हो जाती है?",
        a: "हां। किसी परीक्षा के पेज पर श्रेणी (OBC, SC/ST, PwD, भूतपूर्व सैनिक आदि) चुनते ही उस श्रेणी की संबंधित आयु छूट अपने आप लागू हो जाती है।",
      },
      {
        q: "क्या यह टूल पूरी तरह मुफ्त है?",
        a: "हां, पूरी तरह मुफ्त। यह पूरी तरह आपके ब्राउज़र में चलता है — कोई साइनअप नहीं, और आपकी जन्म तिथि कभी अपलोड या स्टोर नहीं होती।",
      },
      {
        q: "डेटा कितना सटीक है?",
        a: "आयु सीमा और श्रेणी छूट हर परीक्षा के मानक, सार्वजनिक रूप से ज्ञात पैटर्न का पालन करती हैं। नियम हर साल बदल सकते हैं — आवेदन से पहले हमेशा नवीनतम आधिकारिक नोटिफिकेशन ज़रूर देखें।",
      },
      {
        q: "अगर मेरी परीक्षा लिस्ट में नहीं है तो?",
        a: "हम Civil Services, Banking, Railways, Defence, SSC, Engineering, Medical, State PSC, Teaching, Insurance और Police में 85 प्रमुख भारतीय प्रतियोगी परीक्षाएं कवर करते हैं। अगर आपकी अभी लिस्ट में नहीं है, तो दोबारा देखें — हम यह लिस्ट समय-समय पर अपडेट करते हैं।",
      },
    ],
  },
};

export function getAgeCalcStrings(locale?: Locale) {
  return locale === "hi" ? AGE_CALC_STRINGS.hi : AGE_CALC_STRINGS.en;
}
