// UI-chrome-only translation for the syllabus tracker — labels, buttons,
// section headings. Exam data itself (exam names, states, exam types,
// subject/chapter names) comes from the live backend and stays untranslated
// on every locale, same rule as ageCalculatorStrings.ts's own header
// comment: translating that content is a different, much larger effort than
// translating this fixed UI chrome.
import type { Locale } from "./dictionary";

export const SYLLABUS_STRINGS = {
  en: {
    metaTitle: "Syllabus Tracker — Track Your Exam Chapters | Clear Cutoff",
    metaDescription:
      "Pick your exam, level and subjects, then check off chapters as you study them. Free, no sign-up needed, and saved in your browser — log in only if you want to save it to your account.",
    metaOgDescription: "Pick your exam, level and subjects, then check off chapters as you study them. Saved in your browser, no sign-up needed.",
    aboutTitle: "About the Syllabus Tracker",
    aboutBody:
      "Pick your exam, level and subjects, then check off each chapter as you finish it. Your progress is saved in this browser and no sign-up is needed — nothing is uploaded unless you log in and choose to save it to your account. Syllabus data is loaded from Clear Cutoff's exam database.",
    howTitle: "How it works",
    howSteps: [
      "Choose your exam (and its paper or level, if it has one).",
      "Open a subject to see its chapters.",
      "Tick chapters as you complete them and watch your progress grow.",
    ],

    stepperAriaLabel: "Syllabus Tracker progress",
    stepExamLabel: "Exam",
    stepExamSub: "Choose your exam",
    stepPaperLabel: "Paper",
    stepPaperSub: "Select paper",
    stepLevelLabel: "Level",
    stepLevelSub: "Select level",
    stepTrackLabel: "Track",
    stepTrackSub: "Start tracking",
    stepOf: (step: number, total: number) => `Step ${step} of ${total}`,

    myTrackedExamsTitle: "Your tracked exams",
    myTrackedExamsSubtitle: "Pick up where you left off, or add another exam to track.",
    trackMultipleExamsTipTitle: "Track multiple exams",
    trackMultipleExamsTipDescription: "Organize your preparation and monitor progress for every exam in one place.",
    addMoreExam: "Add More Exam",
    addMoreExamHint: "Track your syllabus progress for another exam.",
    addPaper: "Add Paper",
    addPaperHint: "Track another paper of this exam.",
    addLevel: "Add Level",
    addLevelHint: "Track another level of this exam.",
    notTrackedYet: "Not tracked yet",
    completedElsewhere: (examShortName: string) => `Completed already in ${examShortName}`,

    paperNoun: "paper",
    choosePaperHint: "Choose the paper you want to track. You can add the other paper anytime.",
    paperTipTitle: "One paper at a time.",
    paperTipDescription: "You can track another paper of this exam later without losing this one's progress.",

    chooseExamTitle: "Choose your exam",
    chooseExamSubtitle: "Pick the exam you're preparing for to load its syllabus.",
    examTipTitle: "Track. Plan. Clear.",
    examTipDescription: "Select an exam to get started on your preparation journey.",
    searchExamsPlaceholder: "Search exams (e.g. CTET, UPTET, REET...)",
    allStates: "All States",
    examListError: "Couldn't load the exam list. Please refresh and try again.",
    noExamsMatch: "No exams match your search",
    noExamsMatchHint: "Try a different search term or state filter.",
    cantFindExam: "Can't find your exam?",
    cantFindExamHint: "More exams will be added soon. Let us know if you need a specific one.",
    requestExam: "Request an Exam",
    whatsappRequestMessage: "Hi! I'd like to request an exam be added to the Syllabus Tracker.",

    levelNoun: "level",
    subjectNoun: "subject",
    selectNounFor: (noun: string, title: string) => `Select ${noun} for ${title}`,
    chooseNounHint: (noun: string) => `Choose the ${noun} you want to track. You can change or reset it anytime.`,
    levelTipTitle: "Almost there.",
    levelTipDescription: "Pick the level that matches your exam attempt.",
    levelListError: "Couldn't load levels for this exam.",
    noSeparateLevels: "This exam doesn't have separate levels — continuing with the full syllabus.",
    chooseNounWithin: (noun: string, name: string) => `Choose a ${noun} within ${name}`,
    trackCutoffOnly: (name: string) => `Track cutoff for ${name} only`,
    includesRelevantSubjects: "Includes all relevant subjects",
    fullExamTitle: (shortName: string) => `Full ${shortName} (all levels)`,
    trackCutoffAllLevels: "Track cutoff for all levels",
    includesAllSubjectsAndLevels: "Includes all subjects and levels",
    canChangeNounLater: (noun: string) => `You can change the ${noun} later`,
    canChangeNounLaterHint: (noun: string) => `If you want to track a different ${noun}, you can reset and select again anytime.`,
    back: "Back",
    continueLabel: "Continue",

    trackDifferentExam: "Track a different exam",
    allChaptersMastered: "🎉 Every chapter mastered!",
    chaptersMastered: (completed: number, total: number) => `${completed} of ${total} chapters mastered`,
    resetLabel: "Reset",
    searchChaptersPlaceholder: "Search chapters...",
    viewCards: "Cards",
    viewList: "List",
    noChaptersMatch: (query: string) => `No chapters match "${query}"`,
    selectChaptersHint: "Select chapters to start tracking your preparation.",

    sectionsTitle: "Sections",
    sectionsSubtitle: "Select a section to view its chapters",
    chaptersCount: (completed: number, total: number) => `${completed} / ${total} chapters`,

    resetConfirmTitle: "Reset your syllabus tracker?",
    resetConfirmDescription: "This clears everything you've tracked so far — completed chapters and revision dates included. This can't be undone.",
    resetConfirmLabel: "Reset",
    resetCancelLabel: "Cancel",

    syllabusLoadError: "Couldn't load the syllabus for this level.",
    tryAgain: "Try again",

    progressSavedNote: "Your progress is saved in this browser. Log in and tap “Save for Future” to keep it on your account.",

    saveForFuture: "Save for Future",
    saving: "Saving…",
    savedToAccount: "Saved to your account",
    saveFailed: "Couldn't save. Please try again.",
    loginToSaveTitle: "Login to save your progress for future.",
    loginToSaveSubtitle: "Your tracker stays right here — just verify your number.",
    loginToSaveSubmit: "Continue",
    loginToLoadTitle: "Login to load your saved trackers.",
    loginToLoadPrompt: "Saved a tracker before? Log in to load it here.",
    loginLabel: "Log in",
    signedInNote: "You're logged in — trackers you saved appear on this page.",
    logoutLabel: "Log out",
    savedTrackersTitle: "Saved on your account",
    savedTrackersSubtitle: "Trackers you saved earlier. Loading one copies it into this browser.",
    savedDiffers: "Different from this browser",
    savedLoadLabel: "Load",
    savedLoadingList: "Loading your saved trackers…",
    savedListError: "Couldn't load your saved trackers.",
    savedChip: "Saved",
    unsavedChip: "Unsaved changes",
    loadSavedReplaceTitle: "Replace this browser's progress?",
    loadSavedReplaceDescription: "Loading the saved copy replaces the progress you have here for this exam. The copy on your account stays as it is.",
    loadSavedReplaceConfirm: "Load saved copy",
    saveConflictTitle: "Replace your saved copy?",
    saveConflictDescription: "Your account already has a saved copy of this tracker that differs from this browser. Saving will replace it with the progress you have here.",
    saveConflictConfirm: "Replace saved copy",
    saveConflictKeep: "Keep saved copy",
  },
  hi: {
    metaTitle: "सिलेबस ट्रैकर — अपने परीक्षा अध्याय ट्रैक करें | Clear Cutoff",
    metaDescription:
      "अपना एग्जाम, लेवल और विषय चुनें, फिर पढ़ाई करते समय अध्यायों को चेक ऑफ करें। मुफ़्त, साइन-अप की ज़रूरत नहीं, और आपके ब्राउज़र में सेव होता है — अकाउंट में सेव करना चाहें तभी लॉग इन करें।",
    metaOgDescription: "अपना एग्जाम, लेवल और विषय चुनें, फिर पढ़ाई करते समय अध्यायों को चेक ऑफ करें। आपके ब्राउज़र में सेव होता है, साइन-अप की ज़रूरत नहीं।",
    aboutTitle: "सिलेबस ट्रैकर के बारे में",
    aboutBody:
      "अपनी परीक्षा, लेवल और विषय चुनें, फिर हर अध्याय पूरा होते ही उसे टिक करें। आपकी प्रगति इसी ब्राउज़र में सेव होती है और साइन-अप की ज़रूरत नहीं है — जब तक आप लॉग इन करके अकाउंट में सेव न करें, कुछ भी अपलोड नहीं होता। सिलेबस का डेटा Clear Cutoff के परीक्षा डेटाबेस से लोड होता है।",
    howTitle: "यह कैसे काम करता है",
    howSteps: [
      "अपनी परीक्षा चुनें (और अगर हो तो उसका पेपर या लेवल)।",
      "किसी विषय को खोलकर उसके अध्याय देखें।",
      "अध्याय पूरे होते ही उन्हें टिक करें और अपनी प्रगति देखें।",
    ],

    stepperAriaLabel: "सिलेबस ट्रैकर प्रगति",
    stepExamLabel: "एग्जाम",
    stepExamSub: "अपना एग्जाम चुनें",
    stepPaperLabel: "पेपर",
    stepPaperSub: "पेपर चुनें",
    stepLevelLabel: "लेवल",
    stepLevelSub: "लेवल चुनें",
    stepTrackLabel: "ट्रैक",
    stepTrackSub: "ट्रैकिंग शुरू करें",
    stepOf: (step: number, total: number) => `चरण ${step} / ${total}`,

    myTrackedExamsTitle: "आपके ट्रैक किए गए एग्जाम",
    myTrackedExamsSubtitle: "जहां छोड़ा था वहीं से जारी रखें, या ट्रैक करने के लिए कोई और एग्जाम जोड़ें।",
    trackMultipleExamsTipTitle: "कई एग्जाम ट्रैक करें",
    trackMultipleExamsTipDescription: "अपनी तैयारी व्यवस्थित करें और हर एग्जाम की प्रगति एक ही जगह देखें।",
    addMoreExam: "और एग्जाम जोड़ें",
    addMoreExamHint: "किसी और एग्जाम के लिए अपनी सिलेबस प्रगति ट्रैक करें।",
    addPaper: "पेपर जोड़ें",
    addPaperHint: "इस एग्जाम का एक और पेपर ट्रैक करें।",
    addLevel: "लेवल जोड़ें",
    addLevelHint: "इस एग्जाम का एक और लेवल ट्रैक करें।",
    notTrackedYet: "अभी ट्रैक नहीं किया",
    completedElsewhere: (examShortName: string) => `${examShortName} में पहले से पूरा हो चुका है`,

    paperNoun: "पेपर",
    choosePaperHint: "जिस पेपर को ट्रैक करना है उसे चुनें। दूसरा पेपर आप कभी भी जोड़ सकते हैं।",
    paperTipTitle: "एक बार में एक पेपर।",
    paperTipDescription: "इस एग्जाम का दूसरा पेपर आप बाद में भी ट्रैक कर सकते हैं, इससे इस पेपर की प्रगति नहीं मिटेगी।",

    chooseExamTitle: "अपना एग्जाम चुनें",
    chooseExamSubtitle: "जिस एग्जाम की तैयारी कर रहे हैं उसे चुनें ताकि उसका सिलेबस लोड हो सके।",
    examTipTitle: "ट्रैक करें। प्लान करें। क्लियर करें।",
    examTipDescription: "अपनी तैयारी शुरू करने के लिए एक एग्जाम चुनें।",
    searchExamsPlaceholder: "एग्जाम खोजें (जैसे CTET, UPTET, REET...)",
    allStates: "सभी राज्य",
    examListError: "एग्जाम लिस्ट लोड नहीं हो सकी। कृपया रिफ्रेश करके फिर से कोशिश करें।",
    noExamsMatch: "आपकी खोज से कोई एग्जाम मेल नहीं खाता",
    noExamsMatchHint: "कोई दूसरा खोज शब्द या राज्य फ़िल्टर आज़माएं।",
    cantFindExam: "अपना एग्जाम नहीं मिल रहा?",
    cantFindExamHint: "जल्द ही और एग्जाम जोड़े जाएंगे। अगर आपको कोई खास एग्जाम चाहिए तो हमें बताएं।",
    requestExam: "एग्जाम के लिए अनुरोध करें",
    whatsappRequestMessage: "नमस्ते! मैं चाहता/चाहती हूं कि सिलेबस ट्रैकर में एक एग्जाम जोड़ा जाए।",

    levelNoun: "लेवल",
    subjectNoun: "विषय",
    selectNounFor: (noun: string, title: string) => `${title} के लिए ${noun} चुनें`,
    chooseNounHint: (noun: string) => `जिस ${noun} को ट्रैक करना है उसे चुनें। आप इसे कभी भी बदल या रीसेट कर सकते हैं।`,
    levelTipTitle: "बस थोड़ा और बाकी है।",
    levelTipDescription: "अपने एग्जाम अटेम्प्ट से मेल खाने वाला लेवल चुनें।",
    levelListError: "इस एग्जाम के लेवल लोड नहीं हो सके।",
    noSeparateLevels: "इस एग्जाम में अलग लेवल नहीं हैं — पूरे सिलेबस के साथ आगे बढ़ रहे हैं।",
    chooseNounWithin: (noun: string, name: string) => `${name} के अंदर एक ${noun} चुनें`,
    trackCutoffOnly: (name: string) => `सिर्फ़ ${name} के लिए कटऑफ ट्रैक करें`,
    includesRelevantSubjects: "इसमें सभी संबंधित विषय शामिल हैं",
    fullExamTitle: (shortName: string) => `पूरा ${shortName} (सभी लेवल)`,
    trackCutoffAllLevels: "सभी लेवल के लिए कटऑफ ट्रैक करें",
    includesAllSubjectsAndLevels: "इसमें सभी विषय और लेवल शामिल हैं",
    canChangeNounLater: (noun: string) => `आप ${noun} बाद में भी बदल सकते हैं`,
    canChangeNounLaterHint: (noun: string) => `अगर आप कोई दूसरा ${noun} ट्रैक करना चाहते हैं, तो कभी भी रीसेट करके फिर से चुन सकते हैं।`,
    back: "पीछे",
    continueLabel: "जारी रखें",

    trackDifferentExam: "किसी दूसरे एग्जाम को ट्रैक करें",
    allChaptersMastered: "🎉 हर अध्याय पूरा हो गया!",
    chaptersMastered: (completed: number, total: number) => `${total} में से ${completed} अध्याय पूरे हुए`,
    resetLabel: "रीसेट",
    searchChaptersPlaceholder: "अध्याय खोजें...",
    viewCards: "कार्ड्स",
    viewList: "लिस्ट",
    noChaptersMatch: (query: string) => `"${query}" से कोई अध्याय मेल नहीं खाता`,
    selectChaptersHint: "अपनी तैयारी ट्रैक करना शुरू करने के लिए अध्याय चुनें।",

    sectionsTitle: "सेक्शन",
    sectionsSubtitle: "अध्याय देखने के लिए एक सेक्शन चुनें",
    chaptersCount: (completed: number, total: number) => `${total} में से ${completed} अध्याय`,

    resetConfirmTitle: "अपना सिलेबस ट्रैकर रीसेट करें?",
    resetConfirmDescription: "इससे अब तक ट्रैक किया गया सब कुछ हट जाएगा — पूरे किए गए अध्याय और रिवीजन तारीखें भी शामिल हैं। यह पूर्ववत नहीं किया जा सकता।",
    resetConfirmLabel: "रीसेट",
    resetCancelLabel: "रद्द करें",

    syllabusLoadError: "इस लेवल का सिलेबस लोड नहीं हो सका।",
    tryAgain: "फिर से कोशिश करें",

    progressSavedNote: "आपकी प्रगति इस ब्राउज़र में सेव है। इसे अपने अकाउंट में रखने के लिए लॉग इन करें और “भविष्य के लिए सेव करें” दबाएँ।",

    saveForFuture: "भविष्य के लिए सेव करें",
    saving: "सेव हो रहा है…",
    savedToAccount: "अकाउंट में सेव हो गया",
    saveFailed: "सेव नहीं हो सका। कृपया फिर से कोशिश करें।",
    loginToSaveTitle: "अपनी प्रगति भविष्य के लिए सेव करने हेतु लॉग इन करें।",
    loginToSaveSubtitle: "आपका ट्रैकर यहीं रहेगा — बस अपना नंबर वेरिफ़ाई करें।",
    loginToSaveSubmit: "आगे बढ़ें",
    loginToLoadTitle: "अपने सेव किए ट्रैकर लोड करने के लिए लॉग इन करें।",
    loginToLoadPrompt: "पहले कोई ट्रैकर सेव किया था? उसे यहाँ लोड करने के लिए लॉग इन करें।",
    loginLabel: "लॉग इन",
    signedInNote: "आप लॉग इन हैं — आपके सेव किए ट्रैकर इसी पेज पर दिखेंगे।",
    logoutLabel: "लॉग आउट",
    savedTrackersTitle: "आपके अकाउंट में सेव",
    savedTrackersSubtitle: "पहले सेव किए हुए ट्रैकर। लोड करने पर उसकी कॉपी इस ब्राउज़र में आ जाती है।",
    savedDiffers: "इस ब्राउज़र से अलग",
    savedLoadLabel: "लोड करें",
    savedLoadingList: "आपके सेव किए ट्रैकर लोड हो रहे हैं…",
    savedListError: "आपके सेव किए ट्रैकर लोड नहीं हो सके।",
    savedChip: "सेव",
    unsavedChip: "बिना सेव बदलाव",
    loadSavedReplaceTitle: "इस ब्राउज़र की प्रगति बदलें?",
    loadSavedReplaceDescription: "सेव की हुई कॉपी लोड करने पर इस परीक्षा की यहाँ मौजूद प्रगति बदल जाएगी। आपके अकाउंट की कॉपी वैसी ही रहेगी।",
    loadSavedReplaceConfirm: "सेव कॉपी लोड करें",
    saveConflictTitle: "सेव की हुई कॉपी बदलें?",
    saveConflictDescription: "आपके अकाउंट में इस ट्रैकर की एक सेव कॉपी पहले से है जो इस ब्राउज़र से अलग है। सेव करने पर वह यहाँ की प्रगति से बदल जाएगी।",
    saveConflictConfirm: "सेव कॉपी बदलें",
    saveConflictKeep: "सेव कॉपी रखें",
  },
  mr: {
    metaTitle: "अभ्यासक्रम ट्रॅकर — तुमचे परीक्षा प्रकरण ट्रॅक करा | Clear Cutoff",
    metaDescription:
      "तुमची परीक्षा, लेव्हल आणि विषय निवडा, नंतर अभ्यास करताना प्रकरणे चेक ऑफ करा. मोफत, साइन-अपची गरज नाही, आणि तुमच्या ब्राउझरमध्ये सेव्ह होते — अकाउंटमध्ये सेव्ह करायचे असेल तेव्हाच लॉग इन करा.",
    metaOgDescription: "तुमची परीक्षा, लेव्हल आणि विषय निवडा, नंतर अभ्यास करताना प्रकरणे चेक ऑफ करा. तुमच्या ब्राउझरमध्ये सेव्ह होते, साइन-अपची गरज नाही.",
    aboutTitle: "अभ्यासक्रम ट्रॅकरबद्दल",
    aboutBody:
      "तुमची परीक्षा, लेव्हल आणि विषय निवडा, मग प्रत्येक प्रकरण पूर्ण होताच त्यावर टिक करा. तुमची प्रगती याच ब्राउझरमध्ये सेव्ह होते आणि साइन-अपची गरज नाही — तुम्ही लॉग इन करून अकाउंटमध्ये सेव्ह करेपर्यंत काहीही अपलोड होत नाही. अभ्यासक्रमाचा डेटा Clear Cutoff च्या परीक्षा डेटाबेसमधून लोड होतो.",
    howTitle: "हे कसे काम करते",
    howSteps: [
      "तुमची परीक्षा निवडा (आणि असल्यास त्याचा पेपर किंवा लेव्हल).",
      "एखादा विषय उघडून त्यातील प्रकरणे पहा.",
      "प्रकरणे पूर्ण होताच त्यावर टिक करा आणि तुमची प्रगती पहा.",
    ],

    stepperAriaLabel: "अभ्यासक्रम ट्रॅकर प्रगती",
    stepExamLabel: "परीक्षा",
    stepExamSub: "तुमची परीक्षा निवडा",
    stepPaperLabel: "पेपर",
    stepPaperSub: "पेपर निवडा",
    stepLevelLabel: "लेव्हल",
    stepLevelSub: "लेव्हल निवडा",
    stepTrackLabel: "ट्रॅक",
    stepTrackSub: "ट्रॅकिंग सुरू करा",
    stepOf: (step: number, total: number) => `स्टेप ${step} / ${total}`,

    myTrackedExamsTitle: "तुमच्या ट्रॅक केलेल्या परीक्षा",
    myTrackedExamsSubtitle: "जिथे थांबला होता तिथून पुढे सुरू ठेवा, किंवा ट्रॅक करण्यासाठी आणखी एक परीक्षा जोडा.",
    trackMultipleExamsTipTitle: "अनेक परीक्षा ट्रॅक करा",
    trackMultipleExamsTipDescription: "तुमची तयारी व्यवस्थित करा आणि प्रत्येक परीक्षेची प्रगती एकाच ठिकाणी पाहा.",
    addMoreExam: "आणखी परीक्षा जोडा",
    addMoreExamHint: "दुसऱ्या परीक्षेसाठी तुमची अभ्यासक्रम प्रगती ट्रॅक करा.",
    addPaper: "पेपर जोडा",
    addPaperHint: "या परीक्षेचा आणखी एक पेपर ट्रॅक करा.",
    addLevel: "लेव्हल जोडा",
    addLevelHint: "या परीक्षेचा आणखी एक लेव्हल ट्रॅक करा.",
    notTrackedYet: "अजून ट्रॅक केलेले नाही",
    completedElsewhere: (examShortName: string) => `${examShortName} मध्ये आधीच पूर्ण झाले आहे`,

    paperNoun: "पेपर",
    choosePaperHint: "तुम्हाला ट्रॅक करायचा पेपर निवडा. दुसरा पेपर तुम्ही कधीही जोडू शकता.",
    paperTipTitle: "एका वेळी एक पेपर.",
    paperTipDescription: "या परीक्षेचा दुसरा पेपर तुम्ही नंतरही ट्रॅक करू शकता, यामुळे या पेपरची प्रगती मिटणार नाही.",

    chooseExamTitle: "तुमची परीक्षा निवडा",
    chooseExamSubtitle: "तुम्ही ज्या परीक्षेची तयारी करत आहात ती निवडा जेणेकरून तिचा अभ्यासक्रम लोड होईल.",
    examTipTitle: "ट्रॅक करा. प्लॅन करा. क्लियर करा.",
    examTipDescription: "तुमचा तयारीचा प्रवास सुरू करण्यासाठी एक परीक्षा निवडा.",
    searchExamsPlaceholder: "परीक्षा शोधा (उदा. CTET, UPTET, REET...)",
    allStates: "सर्व राज्ये",
    examListError: "परीक्षांची यादी लोड होऊ शकली नाही. कृपया रिफ्रेश करून पुन्हा प्रयत्न करा.",
    noExamsMatch: "तुमच्या शोधाशी कोणतीही परीक्षा जुळत नाही",
    noExamsMatchHint: "वेगळा शोध शब्द किंवा राज्य फिल्टर वापरून पहा.",
    cantFindExam: "तुमची परीक्षा सापडत नाही?",
    cantFindExamHint: "लवकरच आणखी परीक्षा जोडल्या जातील. तुम्हाला एखादी विशिष्ट परीक्षा हवी असल्यास आम्हाला कळवा.",
    requestExam: "परीक्षेसाठी विनंती करा",
    whatsappRequestMessage: "नमस्कार! मला सिलॅबस ट्रॅकरमध्ये एक परीक्षा जोडण्याची विनंती करायची आहे.",

    levelNoun: "लेव्हल",
    subjectNoun: "विषय",
    selectNounFor: (noun: string, title: string) => `${title} साठी ${noun} निवडा`,
    chooseNounHint: (noun: string) => `तुम्हाला ट्रॅक करायचा ${noun} निवडा. तुम्ही तो कधीही बदलू किंवा रीसेट करू शकता.`,
    levelTipTitle: "जवळजवळ पूर्ण झाले.",
    levelTipDescription: "तुमच्या परीक्षेच्या प्रयत्नाशी जुळणारी लेव्हल निवडा.",
    levelListError: "या परीक्षेच्या लेव्हल लोड होऊ शकल्या नाहीत.",
    noSeparateLevels: "या परीक्षेत वेगळ्या लेव्हल नाहीत — संपूर्ण अभ्यासक्रमासह पुढे जात आहोत.",
    chooseNounWithin: (noun: string, name: string) => `${name} मध्ये एक ${noun} निवडा`,
    trackCutoffOnly: (name: string) => `फक्त ${name} साठी कटऑफ ट्रॅक करा`,
    includesRelevantSubjects: "यामध्ये सर्व संबंधित विषयांचा समावेश आहे",
    fullExamTitle: (shortName: string) => `संपूर्ण ${shortName} (सर्व लेव्हल)`,
    trackCutoffAllLevels: "सर्व लेव्हलसाठी कटऑफ ट्रॅक करा",
    includesAllSubjectsAndLevels: "यामध्ये सर्व विषय आणि लेव्हलचा समावेश आहे",
    canChangeNounLater: (noun: string) => `तुम्ही ${noun} नंतरही बदलू शकता`,
    canChangeNounLaterHint: (noun: string) => `तुम्हाला वेगळा ${noun} ट्रॅक करायचा असल्यास, तुम्ही कधीही रीसेट करून पुन्हा निवडू शकता.`,
    back: "मागे",
    continueLabel: "पुढे सुरू ठेवा",

    trackDifferentExam: "वेगळी परीक्षा ट्रॅक करा",
    allChaptersMastered: "🎉 सर्व प्रकरणे पूर्ण झाली!",
    chaptersMastered: (completed: number, total: number) => `${total} पैकी ${completed} प्रकरणे पूर्ण झाली`,
    resetLabel: "रीसेट",
    searchChaptersPlaceholder: "प्रकरणे शोधा...",
    viewCards: "कार्ड्स",
    viewList: "यादी",
    noChaptersMatch: (query: string) => `"${query}" शी कोणतेही प्रकरण जुळत नाही`,
    selectChaptersHint: "तुमची तयारी ट्रॅक करणे सुरू करण्यासाठी प्रकरणे निवडा.",

    sectionsTitle: "विभाग",
    sectionsSubtitle: "प्रकरणे पाहण्यासाठी एक विभाग निवडा",
    chaptersCount: (completed: number, total: number) => `${total} पैकी ${completed} प्रकरणे`,

    resetConfirmTitle: "तुमचा सिलॅबस ट्रॅकर रीसेट करायचा आहे का?",
    resetConfirmDescription: "यामुळे आतापर्यंत ट्रॅक केलेले सर्व काही मिटेल — पूर्ण झालेली प्रकरणे आणि उजळणी तारखांसह. हे पूर्ववत करता येणार नाही.",
    resetConfirmLabel: "रीसेट",
    resetCancelLabel: "रद्द करा",

    syllabusLoadError: "या लेव्हलचा अभ्यासक्रम लोड होऊ शकला नाही.",
    tryAgain: "पुन्हा प्रयत्न करा",

    progressSavedNote: "तुमची प्रगती या ब्राउझरमध्ये सेव्ह आहे. ती तुमच्या अकाउंटमध्ये ठेवण्यासाठी लॉग इन करा आणि “भविष्यासाठी सेव्ह करा” दाबा.",

    saveForFuture: "भविष्यासाठी सेव्ह करा",
    saving: "सेव्ह होत आहे…",
    savedToAccount: "अकाउंटमध्ये सेव्ह झाले",
    saveFailed: "सेव्ह करता आले नाही. कृपया पुन्हा प्रयत्न करा.",
    loginToSaveTitle: "तुमची प्रगती भविष्यासाठी सेव्ह करण्यासाठी लॉग इन करा.",
    loginToSaveSubtitle: "तुमचा ट्रॅकर इथेच राहील — फक्त तुमचा नंबर व्हेरिफाय करा.",
    loginToSaveSubmit: "पुढे जा",
    loginToLoadTitle: "तुमचे सेव्ह केलेले ट्रॅकर लोड करण्यासाठी लॉग इन करा.",
    loginToLoadPrompt: "आधी एखादा ट्रॅकर सेव्ह केला होता? तो इथे लोड करण्यासाठी लॉग इन करा.",
    loginLabel: "लॉग इन",
    signedInNote: "तुम्ही लॉग इन आहात — तुम्ही सेव्ह केलेले ट्रॅकर याच पेजवर दिसतील.",
    logoutLabel: "लॉग आउट",
    savedTrackersTitle: "तुमच्या अकाउंटमध्ये सेव्ह",
    savedTrackersSubtitle: "आधी सेव्ह केलेले ट्रॅकर. लोड केल्यावर त्याची कॉपी या ब्राउझरमध्ये येते.",
    savedDiffers: "या ब्राउझरपेक्षा वेगळे",
    savedLoadLabel: "लोड करा",
    savedLoadingList: "तुमचे सेव्ह केलेले ट्रॅकर लोड होत आहेत…",
    savedListError: "तुमचे सेव्ह केलेले ट्रॅकर लोड होऊ शकले नाहीत.",
    savedChip: "सेव्ह",
    unsavedChip: "सेव्ह न केलेले बदल",
    loadSavedReplaceTitle: "या ब्राउझरमधील प्रगती बदलायची?",
    loadSavedReplaceDescription: "सेव्ह केलेली कॉपी लोड केल्यास या परीक्षेची येथील प्रगती बदलेल. तुमच्या अकाउंटमधील कॉपी तशीच राहील.",
    loadSavedReplaceConfirm: "सेव्ह कॉपी लोड करा",
    saveConflictTitle: "सेव्ह केलेली कॉपी बदलायची?",
    saveConflictDescription: "तुमच्या अकाउंटमध्ये या ट्रॅकरची एक सेव्ह कॉपी आधीच आहे आणि ती या ब्राउझरपेक्षा वेगळी आहे. सेव्ह केल्यास ती येथील प्रगतीने बदलली जाईल.",
    saveConflictConfirm: "सेव्ह कॉपी बदला",
    saveConflictKeep: "सेव्ह कॉपी ठेवा",
  },
};

export function getSyllabusStrings(locale?: Locale) {
  if (locale === "hi") return SYLLABUS_STRINGS.hi;
  if (locale === "mr") return SYLLABUS_STRINGS.mr;
  return SYLLABUS_STRINGS.en;
}
