// UI-chrome-only translation for the syllabus tracker — labels, buttons,
// section headings. Exam data itself (exam names, states, exam types,
// subject/chapter names) comes from the live backend and stays untranslated
// on every locale, same rule as ageCalculatorStrings.ts's own header
// comment: translating that content is a different, much larger effort than
// translating this fixed UI chrome.
import type { Locale } from "./dictionary";

export const SYLLABUS_STRINGS = {
  en: {
    metaTitle: "Syllabus Tracker — Track Your Exam Chapters | Clear Cutoff",
    metaDescription:
      "Pick your exam, level and subjects, then check off chapters as you study them. Free, private, and saved entirely in your browser — nothing is sent to any server.",
    metaOgDescription: "Pick your exam, level and subjects, then check off chapters as you study them. Saved entirely in your browser.",

    stepperAriaLabel: "Syllabus Tracker progress",
    stepExamLabel: "Exam",
    stepExamSub: "Choose your exam",
    stepPaperLabel: "Paper",
    stepPaperSub: "Select paper",
    stepLevelLabel: "Level",
    stepLevelSub: "Select level",
    stepTrackLabel: "Track",
    stepTrackSub: "Start tracking",
    stepOf: (step: number, total: number) => `Step ${step} of ${total}`,

    myTrackedExamsTitle: "Your tracked exams",
    myTrackedExamsSubtitle: "Pick up where you left off, or add another exam to track.",
    trackMultipleExamsTipTitle: "Track multiple exams",
    trackMultipleExamsTipDescription: "Organize your preparation and monitor progress for every exam in one place.",
    addMoreExam: "Add More Exam",
    addMoreExamHint: "Track your syllabus progress for another exam.",
    addPaper: "Add Paper",
    addPaperHint: "Track another paper of this exam.",
    addLevel: "Add Level",
    addLevelHint: "Track another level of this exam.",
    notTrackedYet: "Not tracked yet",
    completedElsewhere: (examShortName: string) => `Completed already in ${examShortName}`,

    paperNoun: "paper",
    choosePaperHint: "Choose the paper you want to track. You can add the other paper anytime.",
    paperTipTitle: "One paper at a time.",
    paperTipDescription: "You can track another paper of this exam later without losing this one's progress.",

    chooseExamTitle: "Choose your exam",
    chooseExamSubtitle: "Pick the exam you're preparing for to load its syllabus.",
    examTipTitle: "Track. Plan. Clear.",
    examTipDescription: "Select an exam to get started on your preparation journey.",
    searchExamsPlaceholder: "Search exams (e.g. CTET, UPTET, REET...)",
    allStates: "All States",
    examListError: "Couldn't load the exam list. Please refresh and try again.",
    noExamsMatch: "No exams match your search",
    noExamsMatchHint: "Try a different search term or state filter.",
    cantFindExam: "Can't find your exam?",
    cantFindExamHint: "More exams will be added soon. Let us know if you need a specific one.",
    requestExam: "Request an Exam",
    whatsappRequestMessage: "Hi! I'd like to request an exam be added to the Syllabus Tracker.",

    levelNoun: "level",
    subjectNoun: "subject",
    selectNounFor: (noun: string, title: string) => `Select ${noun} for ${title}`,
    chooseNounHint: (noun: string) => `Choose the ${noun} you want to track. You can change or reset it anytime.`,
    levelTipTitle: "Almost there.",
    levelTipDescription: "Pick the level that matches your exam attempt.",
    levelListError: "Couldn't load levels for this exam.",
    noSeparateLevels: "This exam doesn't have separate levels — continuing with the full syllabus.",
    chooseNounWithin: (noun: string, name: string) => `Choose a ${noun} within ${name}`,
    trackCutoffOnly: (name: string) => `Track cutoff for ${name} only`,
    includesRelevantSubjects: "Includes all relevant subjects",
    fullExamTitle: (shortName: string) => `Full ${shortName} (all levels)`,
    trackCutoffAllLevels: "Track cutoff for all levels",
    includesAllSubjectsAndLevels: "Includes all subjects and levels",
    canChangeNounLater: (noun: string) => `You can change the ${noun} later`,
    canChangeNounLaterHint: (noun: string) => `If you want to track a different ${noun}, you can reset and select again anytime.`,
    back: "Back",
    continueLabel: "Continue",

    trackDifferentExam: "Track a different exam",
    allChaptersMastered: "🎉 Every chapter mastered!",
    chaptersMastered: (completed: number, total: number) => `${completed} of ${total} chapters mastered`,
    resetLabel: "Reset",
    searchChaptersPlaceholder: "Search chapters...",
    viewCards: "Cards",
    viewList: "List",
    noChaptersMatch: (query: string) => `No chapters match "${query}"`,
    selectChaptersHint: "Select chapters to start tracking your preparation.",

    sectionsTitle: "Sections",
    sectionsSubtitle: "Select a section to view its chapters",
    chaptersCount: (completed: number, total: number) => `${completed} / ${total} chapters`,

    resetConfirmTitle: "Reset your syllabus tracker?",
    resetConfirmDescription: "This clears everything you've tracked so far — completed chapters and revision dates included. This can't be undone.",
    resetConfirmLabel: "Reset",
    resetCancelLabel: "Cancel",

    syllabusLoadError: "Couldn't load the syllabus for this level.",
    tryAgain: "Try again",

    progressSavedNote: "Your progress is saved only in this browser — nothing is sent to any server.",
  },
  hi: {
    metaTitle: "सिलेबस ट्रैकर — अपने परीक्षा अध्याय ट्रैक करें | Clear Cutoff",
    metaDescription:
      "अपना एग्जाम, लेवल और विषय चुनें, फिर पढ़ाई करते समय अध्यायों को चेक ऑफ करें। मुफ़्त, निजी, और पूरी तरह आपके ब्राउज़र में सेव होता है — कुछ भी सर्वर पर नहीं भेजा जाता।",
    metaOgDescription: "अपना एग्जाम, लेवल और विषय चुनें, फिर पढ़ाई करते समय अध्यायों को चेक ऑफ करें। पूरी तरह आपके ब्राउज़र में सेव होता है।",

    stepperAriaLabel: "सिलेबस ट्रैकर प्रगति",
    stepExamLabel: "एग्जाम",
    stepExamSub: "अपना एग्जाम चुनें",
    stepPaperLabel: "पेपर",
    stepPaperSub: "पेपर चुनें",
    stepLevelLabel: "लेवल",
    stepLevelSub: "लेवल चुनें",
    stepTrackLabel: "ट्रैक",
    stepTrackSub: "ट्रैकिंग शुरू करें",
    stepOf: (step: number, total: number) => `चरण ${step} / ${total}`,

    myTrackedExamsTitle: "आपके ट्रैक किए गए एग्जाम",
    myTrackedExamsSubtitle: "जहां छोड़ा था वहीं से जारी रखें, या ट्रैक करने के लिए कोई और एग्जाम जोड़ें।",
    trackMultipleExamsTipTitle: "कई एग्जाम ट्रैक करें",
    trackMultipleExamsTipDescription: "अपनी तैयारी व्यवस्थित करें और हर एग्जाम की प्रगति एक ही जगह देखें।",
    addMoreExam: "और एग्जाम जोड़ें",
    addMoreExamHint: "किसी और एग्जाम के लिए अपनी सिलेबस प्रगति ट्रैक करें।",
    addPaper: "पेपर जोड़ें",
    addPaperHint: "इस एग्जाम का एक और पेपर ट्रैक करें।",
    addLevel: "लेवल जोड़ें",
    addLevelHint: "इस एग्जाम का एक और लेवल ट्रैक करें।",
    notTrackedYet: "अभी ट्रैक नहीं किया",
    completedElsewhere: (examShortName: string) => `${examShortName} में पहले से पूरा हो चुका है`,

    paperNoun: "पेपर",
    choosePaperHint: "जिस पेपर को ट्रैक करना है उसे चुनें। दूसरा पेपर आप कभी भी जोड़ सकते हैं।",
    paperTipTitle: "एक बार में एक पेपर।",
    paperTipDescription: "इस एग्जाम का दूसरा पेपर आप बाद में भी ट्रैक कर सकते हैं, इससे इस पेपर की प्रगति नहीं मिटेगी।",

    chooseExamTitle: "अपना एग्जाम चुनें",
    chooseExamSubtitle: "जिस एग्जाम की तैयारी कर रहे हैं उसे चुनें ताकि उसका सिलेबस लोड हो सके।",
    examTipTitle: "ट्रैक करें। प्लान करें। क्लियर करें।",
    examTipDescription: "अपनी तैयारी शुरू करने के लिए एक एग्जाम चुनें।",
    searchExamsPlaceholder: "एग्जाम खोजें (जैसे CTET, UPTET, REET...)",
    allStates: "सभी राज्य",
    examListError: "एग्जाम लिस्ट लोड नहीं हो सकी। कृपया रिफ्रेश करके फिर से कोशिश करें।",
    noExamsMatch: "आपकी खोज से कोई एग्जाम मेल नहीं खाता",
    noExamsMatchHint: "कोई दूसरा खोज शब्द या राज्य फ़िल्टर आज़माएं।",
    cantFindExam: "अपना एग्जाम नहीं मिल रहा?",
    cantFindExamHint: "जल्द ही और एग्जाम जोड़े जाएंगे। अगर आपको कोई खास एग्जाम चाहिए तो हमें बताएं।",
    requestExam: "एग्जाम के लिए अनुरोध करें",
    whatsappRequestMessage: "नमस्ते! मैं चाहता/चाहती हूं कि सिलेबस ट्रैकर में एक एग्जाम जोड़ा जाए।",

    levelNoun: "लेवल",
    subjectNoun: "विषय",
    selectNounFor: (noun: string, title: string) => `${title} के लिए ${noun} चुनें`,
    chooseNounHint: (noun: string) => `जिस ${noun} को ट्रैक करना है उसे चुनें। आप इसे कभी भी बदल या रीसेट कर सकते हैं।`,
    levelTipTitle: "बस थोड़ा और बाकी है।",
    levelTipDescription: "अपने एग्जाम अटेम्प्ट से मेल खाने वाला लेवल चुनें।",
    levelListError: "इस एग्जाम के लेवल लोड नहीं हो सके।",
    noSeparateLevels: "इस एग्जाम में अलग लेवल नहीं हैं — पूरे सिलेबस के साथ आगे बढ़ रहे हैं।",
    chooseNounWithin: (noun: string, name: string) => `${name} के अंदर एक ${noun} चुनें`,
    trackCutoffOnly: (name: string) => `सिर्फ़ ${name} के लिए कटऑफ ट्रैक करें`,
    includesRelevantSubjects: "इसमें सभी संबंधित विषय शामिल हैं",
    fullExamTitle: (shortName: string) => `पूरा ${shortName} (सभी लेवल)`,
    trackCutoffAllLevels: "सभी लेवल के लिए कटऑफ ट्रैक करें",
    includesAllSubjectsAndLevels: "इसमें सभी विषय और लेवल शामिल हैं",
    canChangeNounLater: (noun: string) => `आप ${noun} बाद में भी बदल सकते हैं`,
    canChangeNounLaterHint: (noun: string) => `अगर आप कोई दूसरा ${noun} ट्रैक करना चाहते हैं, तो कभी भी रीसेट करके फिर से चुन सकते हैं।`,
    back: "पीछे",
    continueLabel: "जारी रखें",

    trackDifferentExam: "किसी दूसरे एग्जाम को ट्रैक करें",
    allChaptersMastered: "🎉 हर अध्याय पूरा हो गया!",
    chaptersMastered: (completed: number, total: number) => `${total} में से ${completed} अध्याय पूरे हुए`,
    resetLabel: "रीसेट",
    searchChaptersPlaceholder: "अध्याय खोजें...",
    viewCards: "कार्ड्स",
    viewList: "लिस्ट",
    noChaptersMatch: (query: string) => `"${query}" से कोई अध्याय मेल नहीं खाता`,
    selectChaptersHint: "अपनी तैयारी ट्रैक करना शुरू करने के लिए अध्याय चुनें।",

    sectionsTitle: "सेक्शन",
    sectionsSubtitle: "अध्याय देखने के लिए एक सेक्शन चुनें",
    chaptersCount: (completed: number, total: number) => `${total} में से ${completed} अध्याय`,

    resetConfirmTitle: "अपना सिलेबस ट्रैकर रीसेट करें?",
    resetConfirmDescription: "इससे अब तक ट्रैक किया गया सब कुछ हट जाएगा — पूरे किए गए अध्याय और रिवीजन तारीखें भी शामिल हैं। यह पूर्ववत नहीं किया जा सकता।",
    resetConfirmLabel: "रीसेट",
    resetCancelLabel: "रद्द करें",

    syllabusLoadError: "इस लेवल का सिलेबस लोड नहीं हो सका।",
    tryAgain: "फिर से कोशिश करें",

    progressSavedNote: "आपकी प्रगति सिर्फ़ इस ब्राउज़र में सेव है — कुछ भी किसी सर्वर पर नहीं भेजा जाता।",
  },
  mr: {
    metaTitle: "अभ्यासक्रम ट्रॅकर — तुमचे परीक्षा प्रकरण ट्रॅक करा | Clear Cutoff",
    metaDescription:
      "तुमची परीक्षा, लेव्हल आणि विषय निवडा, नंतर अभ्यास करताना प्रकरणे चेक ऑफ करा. मोफत, खासगी, आणि पूर्णपणे तुमच्या ब्राउझरमध्ये सेव्ह होते — काहीही सर्व्हरवर पाठवले जात नाही.",
    metaOgDescription: "तुमची परीक्षा, लेव्हल आणि विषय निवडा, नंतर अभ्यास करताना प्रकरणे चेक ऑफ करा. पूर्णपणे तुमच्या ब्राउझरमध्ये सेव्ह होते.",

    stepperAriaLabel: "अभ्यासक्रम ट्रॅकर प्रगती",
    stepExamLabel: "परीक्षा",
    stepExamSub: "तुमची परीक्षा निवडा",
    stepPaperLabel: "पेपर",
    stepPaperSub: "पेपर निवडा",
    stepLevelLabel: "लेव्हल",
    stepLevelSub: "लेव्हल निवडा",
    stepTrackLabel: "ट्रॅक",
    stepTrackSub: "ट्रॅकिंग सुरू करा",
    stepOf: (step: number, total: number) => `स्टेप ${step} / ${total}`,

    myTrackedExamsTitle: "तुमच्या ट्रॅक केलेल्या परीक्षा",
    myTrackedExamsSubtitle: "जिथे थांबला होता तिथून पुढे सुरू ठेवा, किंवा ट्रॅक करण्यासाठी आणखी एक परीक्षा जोडा.",
    trackMultipleExamsTipTitle: "अनेक परीक्षा ट्रॅक करा",
    trackMultipleExamsTipDescription: "तुमची तयारी व्यवस्थित करा आणि प्रत्येक परीक्षेची प्रगती एकाच ठिकाणी पाहा.",
    addMoreExam: "आणखी परीक्षा जोडा",
    addMoreExamHint: "दुसऱ्या परीक्षेसाठी तुमची अभ्यासक्रम प्रगती ट्रॅक करा.",
    addPaper: "पेपर जोडा",
    addPaperHint: "या परीक्षेचा आणखी एक पेपर ट्रॅक करा.",
    addLevel: "लेव्हल जोडा",
    addLevelHint: "या परीक्षेचा आणखी एक लेव्हल ट्रॅक करा.",
    notTrackedYet: "अजून ट्रॅक केलेले नाही",
    completedElsewhere: (examShortName: string) => `${examShortName} मध्ये आधीच पूर्ण झाले आहे`,

    paperNoun: "पेपर",
    choosePaperHint: "तुम्हाला ट्रॅक करायचा पेपर निवडा. दुसरा पेपर तुम्ही कधीही जोडू शकता.",
    paperTipTitle: "एका वेळी एक पेपर.",
    paperTipDescription: "या परीक्षेचा दुसरा पेपर तुम्ही नंतरही ट्रॅक करू शकता, यामुळे या पेपरची प्रगती मिटणार नाही.",

    chooseExamTitle: "तुमची परीक्षा निवडा",
    chooseExamSubtitle: "तुम्ही ज्या परीक्षेची तयारी करत आहात ती निवडा जेणेकरून तिचा अभ्यासक्रम लोड होईल.",
    examTipTitle: "ट्रॅक करा. प्लॅन करा. क्लियर करा.",
    examTipDescription: "तुमचा तयारीचा प्रवास सुरू करण्यासाठी एक परीक्षा निवडा.",
    searchExamsPlaceholder: "परीक्षा शोधा (उदा. CTET, UPTET, REET...)",
    allStates: "सर्व राज्ये",
    examListError: "परीक्षांची यादी लोड होऊ शकली नाही. कृपया रिफ्रेश करून पुन्हा प्रयत्न करा.",
    noExamsMatch: "तुमच्या शोधाशी कोणतीही परीक्षा जुळत नाही",
    noExamsMatchHint: "वेगळा शोध शब्द किंवा राज्य फिल्टर वापरून पहा.",
    cantFindExam: "तुमची परीक्षा सापडत नाही?",
    cantFindExamHint: "लवकरच आणखी परीक्षा जोडल्या जातील. तुम्हाला एखादी विशिष्ट परीक्षा हवी असल्यास आम्हाला कळवा.",
    requestExam: "परीक्षेसाठी विनंती करा",
    whatsappRequestMessage: "नमस्कार! मला सिलॅबस ट्रॅकरमध्ये एक परीक्षा जोडण्याची विनंती करायची आहे.",

    levelNoun: "लेव्हल",
    subjectNoun: "विषय",
    selectNounFor: (noun: string, title: string) => `${title} साठी ${noun} निवडा`,
    chooseNounHint: (noun: string) => `तुम्हाला ट्रॅक करायचा ${noun} निवडा. तुम्ही तो कधीही बदलू किंवा रीसेट करू शकता.`,
    levelTipTitle: "जवळजवळ पूर्ण झाले.",
    levelTipDescription: "तुमच्या परीक्षेच्या प्रयत्नाशी जुळणारी लेव्हल निवडा.",
    levelListError: "या परीक्षेच्या लेव्हल लोड होऊ शकल्या नाहीत.",
    noSeparateLevels: "या परीक्षेत वेगळ्या लेव्हल नाहीत — संपूर्ण अभ्यासक्रमासह पुढे जात आहोत.",
    chooseNounWithin: (noun: string, name: string) => `${name} मध्ये एक ${noun} निवडा`,
    trackCutoffOnly: (name: string) => `फक्त ${name} साठी कटऑफ ट्रॅक करा`,
    includesRelevantSubjects: "यामध्ये सर्व संबंधित विषयांचा समावेश आहे",
    fullExamTitle: (shortName: string) => `संपूर्ण ${shortName} (सर्व लेव्हल)`,
    trackCutoffAllLevels: "सर्व लेव्हलसाठी कटऑफ ट्रॅक करा",
    includesAllSubjectsAndLevels: "यामध्ये सर्व विषय आणि लेव्हलचा समावेश आहे",
    canChangeNounLater: (noun: string) => `तुम्ही ${noun} नंतरही बदलू शकता`,
    canChangeNounLaterHint: (noun: string) => `तुम्हाला वेगळा ${noun} ट्रॅक करायचा असल्यास, तुम्ही कधीही रीसेट करून पुन्हा निवडू शकता.`,
    back: "मागे",
    continueLabel: "पुढे सुरू ठेवा",

    trackDifferentExam: "वेगळी परीक्षा ट्रॅक करा",
    allChaptersMastered: "🎉 सर्व प्रकरणे पूर्ण झाली!",
    chaptersMastered: (completed: number, total: number) => `${total} पैकी ${completed} प्रकरणे पूर्ण झाली`,
    resetLabel: "रीसेट",
    searchChaptersPlaceholder: "प्रकरणे शोधा...",
    viewCards: "कार्ड्स",
    viewList: "यादी",
    noChaptersMatch: (query: string) => `"${query}" शी कोणतेही प्रकरण जुळत नाही`,
    selectChaptersHint: "तुमची तयारी ट्रॅक करणे सुरू करण्यासाठी प्रकरणे निवडा.",

    sectionsTitle: "विभाग",
    sectionsSubtitle: "प्रकरणे पाहण्यासाठी एक विभाग निवडा",
    chaptersCount: (completed: number, total: number) => `${total} पैकी ${completed} प्रकरणे`,

    resetConfirmTitle: "तुमचा सिलॅबस ट्रॅकर रीसेट करायचा आहे का?",
    resetConfirmDescription: "यामुळे आतापर्यंत ट्रॅक केलेले सर्व काही मिटेल — पूर्ण झालेली प्रकरणे आणि उजळणी तारखांसह. हे पूर्ववत करता येणार नाही.",
    resetConfirmLabel: "रीसेट",
    resetCancelLabel: "रद्द करा",

    syllabusLoadError: "या लेव्हलचा अभ्यासक्रम लोड होऊ शकला नाही.",
    tryAgain: "पुन्हा प्रयत्न करा",

    progressSavedNote: "तुमची प्रगती फक्त या ब्राउझरमध्ये सेव्ह आहे — काहीही कोणत्याही सर्व्हरवर पाठवले जात नाही.",
  },
};

export function getSyllabusStrings(locale?: Locale) {
  if (locale === "hi") return SYLLABUS_STRINGS.hi;
  if (locale === "mr") return SYLLABUS_STRINGS.mr;
  return SYLLABUS_STRINGS.en;
}
