import ProtectedPage from "@/components/features/auth/ProtectedPage";
import { Metadata } from "next";
import React from "react";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",

};
export default function OnboardingLayout({ children }: { children: React.ReactNode }) {
  return (
    <ProtectedPage>
      <div className="flex flex-col min-h-screen ">
        <main className="flex-1">{children}</main>
      </div>
    </ProtectedPage>
  );
}
