// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "common": {
    "continueFree": "Continue Free Prep",
    "continueFreeShort": "Continue for Free",
    "startFree": "Start for free"
  },
  "nav": {
    "pricing": "Pricing",
    "features": "Features",
    "faqs": "FAQs"
  },
  "footer": {
    "phone": "Phone",
    "whatsapp": "WhatsApp",
    "privacy": "Policy",
    "terms": "Terms & Conditions",
    "refund": "Refund",
    "contact": "Contact",
    "faq": "FAQ",
    "ageCalculator": "Age Eligibility Calculator",
    "rights": "All rights reserved!"
  }
};
export default messages;