name = "clearcut-tools-router"
main = "src/index.ts"
compatibility_date = "2026-08-11"

routes = [
	{ pattern = "clearcutoff.in/tools", zone_name = "clearcutoff.in" },
	{ pattern = "clearcutoff.in/tools/resizer", zone_name = "clearcutoff.in" },
	{ pattern = "clearcutoff.in/tools/resizer/*", zone_name = "clearcutoff.in" },
	{ pattern = "clearcutoff.in/hi/tools/resizer", zone_name = "clearcutoff.in" },
	{ pattern = "clearcutoff.in/hi/tools/resizer/*", zone_name = "clearcutoff.in" },
]

[vars]
PAGES_ORIGIN = "https://clearcut-tools.pages.dev"
